var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/app.ts
import cookieParser from "cookie-parser";
import express from "express";
import cors from "cors";

// src/config/index.ts
import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(process.cwd(), ".env") });
var config_default = {
  port: process.env.PORT,
  app_url: process.env.APP_URL,
  database_url: process.env.DATABASE_URL,
  bcrypt_hash_pass: process.env.BCRYPT_HASH_PASS,
  access_token_secret_key: process.env.ACCESS_TOKEN_SECRET_KEY,
  refresh_token_secret_key: process.env.REFRESH_TOKEN_SECRET_KEY,
  access_token_expire_in: process.env.ACCESS_TOKEN_EXPIRE_IN,
  refresh_token_expire_in: process.env.REFRESH_TOKEN_EXPIRE_IN,
  stripe_secret_key: process.env.STRIPE_SECRET_KEY,
  stripe_secret_price_key: process.env.STRIPE_SECRET_PRICE_KEY,
  cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  cloudinary_api_key: process.env.CLOUDINARY_API_KEY,
  cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET,
  google_client_id: process.env.GOOGLE_CLIENT_ID,
  node_env: process.env.NODE_ENV || "development"
};

// src/modular/auth/auth.route.ts
import { Router } from "express";

// src/modular/auth/auth.service.ts
import { OAuth2Client } from "google-auth-library";
import bcrypt from "bcryptjs";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path2 from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.8.0",
  "engineVersion": "3c6e192761c0362d496ed980de936e2f3cebcd3a",
  "activeProvider": "postgresql",
  "inlineSchema": 'model Category {\n  id   String @id @default(uuid())\n  name String @unique\n\n  createdBy String?\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  admin User?  @relation(fields: [createdBy], references: [id])\n  gear  Gear[]\n\n  @@map("categories")\n}\n\nenum UserRole {\n  ADMIN\n  PROVIDER\n  CUSTOMER\n}\n\nenum UserStatus {\n  ACTIVE\n  BLOCKED\n}\n\nenum GearStatus {\n  AVAILABLE\n  UNAVAILABLE\n}\n\nenum RentalStatus {\n  PLACED\n  CONFIRMED\n  PAID\n  PICKED_UP\n  RETURNED\n  CANCELLED\n}\n\nenum PaymentStatus {\n  PENDING\n  PAID\n  FAILED\n  CANCELLED\n}\n\nmodel Gear {\n  id String @id @default(uuid())\n\n  title       String\n  description String\n\n  brand String\n\n  pricePerDay Float\n\n  quantity Int\n\n  image String?\n\n  status GearStatus @default(AVAILABLE)\n\n  categoryId String\n  category   Category @relation(fields: [categoryId], references: [id])\n\n  providerId String\n  provider   User   @relation(fields: [providerId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n\n  updatedAt DateTime @updatedAt\n\n  rental Rental[]\n  review Review[]\n\n  @@unique([title, brand, providerId])\n  @@index([categoryId])\n  @@index([providerId])\n  @@map("gears")\n}\n\nmodel Payment {\n  id String @id @default(uuid())\n\n  amount   Decimal @db.Decimal(10, 2)\n  currency String  @default("usd")\n\n  status PaymentStatus @default(PENDING)\n\n  transactionId String? @unique\n  paymentMethod String?\n\n  rentalId String @unique\n  rental   Rental @relation(fields: [rentalId], references: [id])\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([rentalId])\n  @@map("payments")\n}\n\nmodel Rental {\n  id        String   @id @default(uuid())\n  startDate DateTime\n  endDate   DateTime\n  totalDays Int\n\n  totalPrice Float\n  status     RentalStatus @default(PLACED)\n\n  customerId String\n  customer   User   @relation(fields: [customerId], references: [id])\n\n  gearId String\n  gear   Gear   @relation(fields: [gearId], references: [id])\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  review  Review?\n  payment Payment[]\n\n  @@index([customerId])\n  @@index([gearId])\n  @@map("rentals")\n}\n\nmodel Review {\n  id      String  @id @default(uuid())\n  rating  Int\n  comment String?\n\n  customerId String\n  customer   User   @relation(fields: [customerId], references: [id])\n\n  gearId String\n  gear   Gear   @relation(fields: [gearId], references: [id])\n\n  rentalId String @unique\n  rental   Rental @relation(fields: [rentalId], references: [id])\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([customerId])\n  @@index([gearId])\n  @@index([rentalId])\n  @@map("reviews")\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Get a free hosted Postgres database in seconds: `npx create-db`\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id       String     @id @default(uuid())\n  name     String\n  password String\n  email    String     @unique\n  photoUrl String?\n  role     UserRole\n  status   UserStatus @default(ACTIVE)\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  gear     Gear[]\n  rental   Rental[]\n  reviews  Review[]\n  category Category[]\n\n  @@map("users")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"createdBy","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"admin","kind":"object","type":"User","relationName":"CategoryToUser"},{"name":"gear","kind":"object","type":"Gear","relationName":"CategoryToGear"}],"dbName":"categories"},"Gear":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"title","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"brand","kind":"scalar","type":"String"},{"name":"pricePerDay","kind":"scalar","type":"Float"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"image","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"GearStatus"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToGear"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"provider","kind":"object","type":"User","relationName":"GearToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"rental","kind":"object","type":"Rental","relationName":"GearToRental"},{"name":"review","kind":"object","type":"Review","relationName":"GearToReview"}],"dbName":"gears"},"Payment":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"amount","kind":"scalar","type":"Decimal"},{"name":"currency","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"PaymentStatus"},{"name":"transactionId","kind":"scalar","type":"String"},{"name":"paymentMethod","kind":"scalar","type":"String"},{"name":"rentalId","kind":"scalar","type":"String"},{"name":"rental","kind":"object","type":"Rental","relationName":"PaymentToRental"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"payments"},"Rental":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"startDate","kind":"scalar","type":"DateTime"},{"name":"endDate","kind":"scalar","type":"DateTime"},{"name":"totalDays","kind":"scalar","type":"Int"},{"name":"totalPrice","kind":"scalar","type":"Float"},{"name":"status","kind":"enum","type":"RentalStatus"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"customer","kind":"object","type":"User","relationName":"RentalToUser"},{"name":"gearId","kind":"scalar","type":"String"},{"name":"gear","kind":"object","type":"Gear","relationName":"GearToRental"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"review","kind":"object","type":"Review","relationName":"RentalToReview"},{"name":"payment","kind":"object","type":"Payment","relationName":"PaymentToRental"}],"dbName":"rentals"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"customer","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"gearId","kind":"scalar","type":"String"},{"name":"gear","kind":"object","type":"Gear","relationName":"GearToReview"},{"name":"rentalId","kind":"scalar","type":"String"},{"name":"rental","kind":"object","type":"Rental","relationName":"RentalToReview"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"reviews"},"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"photoUrl","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"UserRole"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"gear","kind":"object","type":"Gear","relationName":"GearToUser"},{"name":"rental","kind":"object","type":"Rental","relationName":"RentalToUser"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToUser"}],"dbName":"users"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","category","provider","customer","gear","rental","review","payment","_count","reviews","admin","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","data","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","create","update","Category.upsertOne","Category.deleteOne","Category.deleteMany","having","_min","_max","Category.groupBy","Category.aggregate","Gear.findUnique","Gear.findUniqueOrThrow","Gear.findFirst","Gear.findFirstOrThrow","Gear.findMany","Gear.createOne","Gear.createMany","Gear.createManyAndReturn","Gear.updateOne","Gear.updateMany","Gear.updateManyAndReturn","Gear.upsertOne","Gear.deleteOne","Gear.deleteMany","_avg","_sum","Gear.groupBy","Gear.aggregate","Payment.findUnique","Payment.findUniqueOrThrow","Payment.findFirst","Payment.findFirstOrThrow","Payment.findMany","Payment.createOne","Payment.createMany","Payment.createManyAndReturn","Payment.updateOne","Payment.updateMany","Payment.updateManyAndReturn","Payment.upsertOne","Payment.deleteOne","Payment.deleteMany","Payment.groupBy","Payment.aggregate","Rental.findUnique","Rental.findUniqueOrThrow","Rental.findFirst","Rental.findFirstOrThrow","Rental.findMany","Rental.createOne","Rental.createMany","Rental.createManyAndReturn","Rental.updateOne","Rental.updateMany","Rental.updateManyAndReturn","Rental.upsertOne","Rental.deleteOne","Rental.deleteMany","Rental.groupBy","Rental.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","User.upsertOne","User.deleteOne","User.deleteMany","User.groupBy","User.aggregate","AND","OR","NOT","id","name","password","email","photoUrl","UserRole","role","UserStatus","status","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","every","some","none","rating","comment","customerId","gearId","rentalId","startDate","endDate","totalDays","totalPrice","RentalStatus","amount","currency","PaymentStatus","transactionId","paymentMethod","title","description","brand","pricePerDay","quantity","image","GearStatus","categoryId","providerId","createdBy","title_brand_providerId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "1AM9YAoGAADDAQAgDAAA3gEAIHUAAN0BADB2AAAbABB3AADdAQAweAEAAAABeQEAAAABgQFAAMIBACGCAUAAwgEAIakBAQC_AQAhAQAAAAEAIBADAADGAQAgBgAAwwEAIAcAAMQBACALAADFAQAgdQAAvQEAMHYAAAMAEHcAAL0BADB4AQC-AQAheQEAvgEAIXoBAL4BACF7AQC-AQAhfAEAvwEAIX4AAMABfiKAAQAAwQGAASKBAUAAwgEAIYIBQADCAQAhAQAAAAMAIBMDAADvAQAgBAAA4QEAIAcAAMQBACAIAADFAQAgdQAA7QEAMHYAAAUAEHcAAO0BADB4AQC-AQAhgAEAAO4BpwEigQFAAMIBACGCAUAAwgEAIaABAQC-AQAhoQEBAL4BACGiAQEAvgEAIaMBCADoAQAhpAECAOABACGlAQEAvwEAIacBAQC-AQAhqAEBAL4BACEFAwAAnwMAIAQAAJoDACAHAAD8AgAgCAAA_QIAIKUBAADwAQAgFAMAAO8BACAEAADhAQAgBwAAxAEAIAgAAMUBACB1AADtAQAwdgAABQAQdwAA7QEAMHgBAAAAAYABAADuAacBIoEBQADCAQAhggFAAMIBACGgAQEAvgEAIaEBAQC-AQAhogEBAL4BACGjAQgA6AEAIaQBAgDgAQAhpQEBAL8BACGnAQEAvgEAIagBAQC-AQAhqgEAAOwBACADAAAABQAgAQAABgAwAgAABwAgEQUAAOEBACAGAADiAQAgCAAA6gEAIAkAAOsBACB1AADnAQAwdgAACQAQdwAA5wEAMHgBAL4BACGAAQAA6QGbASKBAUAAwgEAIYIBQADCAQAhkwEBAL4BACGUAQEAvgEAIZYBQADCAQAhlwFAAMIBACGYAQIA4AEAIZkBCADoAQAhBAUAAJoDACAGAACbAwAgCAAAnQMAIAkAAJ4DACARBQAA4QEAIAYAAOIBACAIAADqAQAgCQAA6wEAIHUAAOcBADB2AAAJABB3AADnAQAweAEAAAABgAEAAOkBmwEigQFAAMIBACGCAUAAwgEAIZMBAQC-AQAhlAEBAL4BACGWAUAAwgEAIZcBQADCAQAhmAECAOABACGZAQgA6AEAIQMAAAAJACABAAAKADACAAALACAOBQAA4QEAIAYAAOIBACAHAADjAQAgdQAA3wEAMHYAAA0AEHcAAN8BADB4AQC-AQAhgQFAAMIBACGCAUAAwgEAIZEBAgDgAQAhkgEBAL8BACGTAQEAvgEAIZQBAQC-AQAhlQEBAL4BACEBAAAADQAgDQcAAOMBACB1AADkAQAwdgAADwAQdwAA5AEAMHgBAL4BACGAAQAA5gGeASKBAUAAwgEAIYIBQADCAQAhlQEBAL4BACGbARAA5QEAIZwBAQC-AQAhngEBAL8BACGfAQEAvwEAIQMHAACcAwAgngEAAPABACCfAQAA8AEAIA0HAADjAQAgdQAA5AEAMHYAAA8AEHcAAOQBADB4AQAAAAGAAQAA5gGeASKBAUAAwgEAIYIBQADCAQAhlQEBAAAAAZsBEADlAQAhnAEBAL4BACGeAQEAAAABnwEBAL8BACEDAAAADwAgAQAAEAAwAgAAEQAgAQAAAA8AIAQFAACaAwAgBgAAmwMAIAcAAJwDACCSAQAA8AEAIA4FAADhAQAgBgAA4gEAIAcAAOMBACB1AADfAQAwdgAADQAQdwAA3wEAMHgBAAAAAYEBQADCAQAhggFAAMIBACGRAQIA4AEAIZIBAQC_AQAhkwEBAL4BACGUAQEAvgEAIZUBAQAAAAEDAAAADQAgAQAAFAAwAgAAFQAgAQAAAAkAIAEAAAANACADAAAACQAgAQAACgAwAgAACwAgAwAAAA0AIAEAABQAMAIAABUAIAoGAADDAQAgDAAA3gEAIHUAAN0BADB2AAAbABB3AADdAQAweAEAvgEAIXkBAL4BACGBAUAAwgEAIYIBQADCAQAhqQEBAL8BACEDBgAA-wIAIAwAAJoDACCpAQAA8AEAIAMAAAAbACABAAAcADACAAABACABAAAABQAgAQAAAAkAIAEAAAANACABAAAAGwAgAwAAAAUAIAEAAAYAMAIAAAcAIAEAAAAFACABAAAAAQAgAwAAABsAIAEAABwAMAIAAAEAIAMAAAAbACABAAAcADACAAABACADAAAAGwAgAQAAHAAwAgAAAQAgBwYAANcCACAMAACZAwAgeAEAAAABeQEAAAABgQFAAAAAAYIBQAAAAAGpAQEAAAABARIAACgAIAV4AQAAAAF5AQAAAAGBAUAAAAABggFAAAAAAakBAQAAAAEBEgAAKgAwARIAACoAMAEAAAADACAHBgAAiAIAIAwAAJgDACB4AQD0AQAheQEA9AEAIYEBQAD4AQAhggFAAPgBACGpAQEA9QEAIQIAAAABACASAAAuACAFeAEA9AEAIXkBAPQBACGBAUAA-AEAIYIBQAD4AQAhqQEBAPUBACECAAAAGwAgEgAAMAAgAgAAABsAIBIAADAAIAEAAAADACADAAAAAQAgGQAAKAAgGgAALgAgAQAAAAEAIAEAAAAbACAECgAAlQMAIB8AAJcDACAgAACWAwAgqQEAAPABACAIdQAA3AEAMHYAADgAEHcAANwBADB4AQCsAQAheQEArAEAIYEBQACwAQAhggFAALABACGpAQEArQEAIQMAAAAbACABAAA3ADAeAAA4ACADAAAAGwAgAQAAHAAwAgAAAQAgAQAAAAcAIAEAAAAHACADAAAABQAgAQAABgAwAgAABwAgAwAAAAUAIAEAAAYAMAIAAAcAIAMAAAAFACABAAAGADACAAAHACAQAwAA9gIAIAQAANMCACAHAADUAgAgCAAA1QIAIHgBAAAAAYABAAAApwECgQFAAAAAAYIBQAAAAAGgAQEAAAABoQEBAAAAAaIBAQAAAAGjAQgAAAABpAECAAAAAaUBAQAAAAGnAQEAAAABqAEBAAAAAQESAABAACAMeAEAAAABgAEAAACnAQKBAUAAAAABggFAAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBCAAAAAGkAQIAAAABpQEBAAAAAacBAQAAAAGoAQEAAAABARIAAEIAMAESAABCADAQAwAA9AIAIAQAAJcCACAHAACYAgAgCAAAmQIAIHgBAPQBACGAAQAAlQKnASKBAUAA-AEAIYIBQAD4AQAhoAEBAPQBACGhAQEA9AEAIaIBAQD0AQAhowEIAJMCACGkAQIAlAIAIaUBAQD1AQAhpwEBAPQBACGoAQEA9AEAIQIAAAAHACASAABFACAMeAEA9AEAIYABAACVAqcBIoEBQAD4AQAhggFAAPgBACGgAQEA9AEAIaEBAQD0AQAhogEBAPQBACGjAQgAkwIAIaQBAgCUAgAhpQEBAPUBACGnAQEA9AEAIagBAQD0AQAhAgAAAAUAIBIAAEcAIAIAAAAFACASAABHACADAAAABwAgGQAAQAAgGgAARQAgAQAAAAcAIAEAAAAFACAGCgAAkAMAIB8AAJMDACAgAACSAwAgMQAAkQMAIDIAAJQDACClAQAA8AEAIA91AADYAQAwdgAATgAQdwAA2AEAMHgBAKwBACGAAQAA2QGnASKBAUAAsAEAIYIBQACwAQAhoAEBAKwBACGhAQEArAEAIaIBAQCsAQAhowEIAMwBACGkAQIAyAEAIaUBAQCtAQAhpwEBAKwBACGoAQEArAEAIQMAAAAFACABAABNADAeAABOACADAAAABQAgAQAABgAwAgAABwAgAQAAABEAIAEAAAARACADAAAADwAgAQAAEAAwAgAAEQAgAwAAAA8AIAEAABAAMAIAABEAIAMAAAAPACABAAAQADACAAARACAKBwAAjwMAIHgBAAAAAYABAAAAngECgQFAAAAAAYIBQAAAAAGVAQEAAAABmwEQAAAAAZwBAQAAAAGeAQEAAAABnwEBAAAAAQESAABWACAJeAEAAAABgAEAAACeAQKBAUAAAAABggFAAAAAAZUBAQAAAAGbARAAAAABnAEBAAAAAZ4BAQAAAAGfAQEAAAABARIAAFgAMAESAABYADAKBwAAjgMAIHgBAPQBACGAAQAAxAKeASKBAUAA-AEAIYIBQAD4AQAhlQEBAPQBACGbARAAwwIAIZwBAQD0AQAhngEBAPUBACGfAQEA9QEAIQIAAAARACASAABbACAJeAEA9AEAIYABAADEAp4BIoEBQAD4AQAhggFAAPgBACGVAQEA9AEAIZsBEADDAgAhnAEBAPQBACGeAQEA9QEAIZ8BAQD1AQAhAgAAAA8AIBIAAF0AIAIAAAAPACASAABdACADAAAAEQAgGQAAVgAgGgAAWwAgAQAAABEAIAEAAAAPACAHCgAAiQMAIB8AAIwDACAgAACLAwAgMQAAigMAIDIAAI0DACCeAQAA8AEAIJ8BAADwAQAgDHUAANEBADB2AABkABB3AADRAQAweAEArAEAIYABAADTAZ4BIoEBQACwAQAhggFAALABACGVAQEArAEAIZsBEADSAQAhnAEBAKwBACGeAQEArQEAIZ8BAQCtAQAhAwAAAA8AIAEAAGMAMB4AAGQAIAMAAAAPACABAAAQADACAAARACABAAAACwAgAQAAAAsAIAMAAAAJACABAAAKADACAAALACADAAAACQAgAQAACgAwAgAACwAgAwAAAAkAIAEAAAoAMAIAAAsAIA4FAADPAgAgBgAA6wIAIAgAANACACAJAADRAgAgeAEAAAABgAEAAACbAQKBAUAAAAABggFAAAAAAZMBAQAAAAGUAQEAAAABlgFAAAAAAZcBQAAAAAGYAQIAAAABmQEIAAAAAQESAABsACAKeAEAAAABgAEAAACbAQKBAUAAAAABggFAAAAAAZMBAQAAAAGUAQEAAAABlgFAAAAAAZcBQAAAAAGYAQIAAAABmQEIAAAAAQESAABuADABEgAAbgAwDgUAALYCACAGAADpAgAgCAAAtwIAIAkAALgCACB4AQD0AQAhgAEAALQCmwEigQFAAPgBACGCAUAA-AEAIZMBAQD0AQAhlAEBAPQBACGWAUAA-AEAIZcBQAD4AQAhmAECAJQCACGZAQgAkwIAIQIAAAALACASAABxACAKeAEA9AEAIYABAAC0ApsBIoEBQAD4AQAhggFAAPgBACGTAQEA9AEAIZQBAQD0AQAhlgFAAPgBACGXAUAA-AEAIZgBAgCUAgAhmQEIAJMCACECAAAACQAgEgAAcwAgAgAAAAkAIBIAAHMAIAMAAAALACAZAABsACAaAABxACABAAAACwAgAQAAAAkAIAUKAACEAwAgHwAAhwMAICAAAIYDACAxAACFAwAgMgAAiAMAIA11AADLAQAwdgAAegAQdwAAywEAMHgBAKwBACGAAQAAzQGbASKBAUAAsAEAIYIBQACwAQAhkwEBAKwBACGUAQEArAEAIZYBQACwAQAhlwFAALABACGYAQIAyAEAIZkBCADMAQAhAwAAAAkAIAEAAHkAMB4AAHoAIAMAAAAJACABAAAKADACAAALACABAAAAFQAgAQAAABUAIAMAAAANACABAAAUADACAAAVACADAAAADQAgAQAAFAAwAgAAFQAgAwAAAA0AIAEAABQAMAIAABUAIAsFAACoAgAgBgAAzQIAIAcAAKkCACB4AQAAAAGBAUAAAAABggFAAAAAAZEBAgAAAAGSAQEAAAABkwEBAAAAAZQBAQAAAAGVAQEAAAABARIAAIIBACAIeAEAAAABgQFAAAAAAYIBQAAAAAGRAQIAAAABkgEBAAAAAZMBAQAAAAGUAQEAAAABlQEBAAAAAQESAACEAQAwARIAAIQBADALBQAApQIAIAYAAMwCACAHAACmAgAgeAEA9AEAIYEBQAD4AQAhggFAAPgBACGRAQIAlAIAIZIBAQD1AQAhkwEBAPQBACGUAQEA9AEAIZUBAQD0AQAhAgAAABUAIBIAAIcBACAIeAEA9AEAIYEBQAD4AQAhggFAAPgBACGRAQIAlAIAIZIBAQD1AQAhkwEBAPQBACGUAQEA9AEAIZUBAQD0AQAhAgAAAA0AIBIAAIkBACACAAAADQAgEgAAiQEAIAMAAAAVACAZAACCAQAgGgAAhwEAIAEAAAAVACABAAAADQAgBgoAAP8CACAfAACCAwAgIAAAgQMAIDEAAIADACAyAACDAwAgkgEAAPABACALdQAAxwEAMHYAAJABABB3AADHAQAweAEArAEAIYEBQACwAQAhggFAALABACGRAQIAyAEAIZIBAQCtAQAhkwEBAKwBACGUAQEArAEAIZUBAQCsAQAhAwAAAA0AIAEAAI8BADAeAACQAQAgAwAAAA0AIAEAABQAMAIAABUAIBADAADGAQAgBgAAwwEAIAcAAMQBACALAADFAQAgdQAAvQEAMHYAAAMAEHcAAL0BADB4AQAAAAF5AQC-AQAhegEAvgEAIXsBAAAAAXwBAL8BACF-AADAAX4igAEAAMEBgAEigQFAAMIBACGCAUAAwgEAIQEAAACTAQAgAQAAAJMBACAFAwAA_gIAIAYAAPsCACAHAAD8AgAgCwAA_QIAIHwAAPABACADAAAAAwAgAQAAlgEAMAIAAJMBACADAAAAAwAgAQAAlgEAMAIAAJMBACADAAAAAwAgAQAAlgEAMAIAAJMBACANAwAA-gIAIAYAAPcCACAHAAD4AgAgCwAA-QIAIHgBAAAAAXkBAAAAAXoBAAAAAXsBAAAAAXwBAAAAAX4AAAB-AoABAAAAgAECgQFAAAAAAYIBQAAAAAEBEgAAmgEAIAl4AQAAAAF5AQAAAAF6AQAAAAF7AQAAAAF8AQAAAAF-AAAAfgKAAQAAAIABAoEBQAAAAAGCAUAAAAABARIAAJwBADABEgAAnAEAMA0DAAD8AQAgBgAA-QEAIAcAAPoBACALAAD7AQAgeAEA9AEAIXkBAPQBACF6AQD0AQAhewEA9AEAIXwBAPUBACF-AAD2AX4igAEAAPcBgAEigQFAAPgBACGCAUAA-AEAIQIAAACTAQAgEgAAnwEAIAl4AQD0AQAheQEA9AEAIXoBAPQBACF7AQD0AQAhfAEA9QEAIX4AAPYBfiKAAQAA9wGAASKBAUAA-AEAIYIBQAD4AQAhAgAAAAMAIBIAAKEBACACAAAAAwAgEgAAoQEAIAMAAACTAQAgGQAAmgEAIBoAAJ8BACABAAAAkwEAIAEAAAADACAECgAA8QEAIB8AAPMBACAgAADyAQAgfAAA8AEAIAx1AACrAQAwdgAAqAEAEHcAAKsBADB4AQCsAQAheQEArAEAIXoBAKwBACF7AQCsAQAhfAEArQEAIX4AAK4BfiKAAQAArwGAASKBAUAAsAEAIYIBQACwAQAhAwAAAAMAIAEAAKcBADAeAACoAQAgAwAAAAMAIAEAAJYBADACAACTAQAgDHUAAKsBADB2AACoAQAQdwAAqwEAMHgBAKwBACF5AQCsAQAhegEArAEAIXsBAKwBACF8AQCtAQAhfgAArgF-IoABAACvAYABIoEBQACwAQAhggFAALABACEOCgAAsgEAIB8AALwBACAgAAC8AQAggwEBAAAAAYQBAQAAAASFAQEAAAAEhgEBAAAAAYcBAQAAAAGIAQEAAAABiQEBAAAAAYoBAQC7AQAhiwEBAAAAAYwBAQAAAAGNAQEAAAABDgoAALkBACAfAAC6AQAgIAAAugEAIIMBAQAAAAGEAQEAAAAFhQEBAAAABYYBAQAAAAGHAQEAAAABiAEBAAAAAYkBAQAAAAGKAQEAuAEAIYsBAQAAAAGMAQEAAAABjQEBAAAAAQcKAACyAQAgHwAAtwEAICAAALcBACCDAQAAAH4ChAEAAAB-CIUBAAAAfgiKAQAAtgF-IgcKAACyAQAgHwAAtQEAICAAALUBACCDAQAAAIABAoQBAAAAgAEIhQEAAACAAQiKAQAAtAGAASILCgAAsgEAIB8AALMBACAgAACzAQAggwFAAAAAAYQBQAAAAASFAUAAAAAEhgFAAAAAAYcBQAAAAAGIAUAAAAABiQFAAAAAAYoBQACxAQAhCwoAALIBACAfAACzAQAgIAAAswEAIIMBQAAAAAGEAUAAAAAEhQFAAAAABIYBQAAAAAGHAUAAAAABiAFAAAAAAYkBQAAAAAGKAUAAsQEAIQiDAQIAAAABhAECAAAABIUBAgAAAASGAQIAAAABhwECAAAAAYgBAgAAAAGJAQIAAAABigECALIBACEIgwFAAAAAAYQBQAAAAASFAUAAAAAEhgFAAAAAAYcBQAAAAAGIAUAAAAABiQFAAAAAAYoBQACzAQAhBwoAALIBACAfAAC1AQAgIAAAtQEAIIMBAAAAgAEChAEAAACAAQiFAQAAAIABCIoBAAC0AYABIgSDAQAAAIABAoQBAAAAgAEIhQEAAACAAQiKAQAAtQGAASIHCgAAsgEAIB8AALcBACAgAAC3AQAggwEAAAB-AoQBAAAAfgiFAQAAAH4IigEAALYBfiIEgwEAAAB-AoQBAAAAfgiFAQAAAH4IigEAALcBfiIOCgAAuQEAIB8AALoBACAgAAC6AQAggwEBAAAAAYQBAQAAAAWFAQEAAAAFhgEBAAAAAYcBAQAAAAGIAQEAAAABiQEBAAAAAYoBAQC4AQAhiwEBAAAAAYwBAQAAAAGNAQEAAAABCIMBAgAAAAGEAQIAAAAFhQECAAAABYYBAgAAAAGHAQIAAAABiAECAAAAAYkBAgAAAAGKAQIAuQEAIQuDAQEAAAABhAEBAAAABYUBAQAAAAWGAQEAAAABhwEBAAAAAYgBAQAAAAGJAQEAAAABigEBALoBACGLAQEAAAABjAEBAAAAAY0BAQAAAAEOCgAAsgEAIB8AALwBACAgAAC8AQAggwEBAAAAAYQBAQAAAASFAQEAAAAEhgEBAAAAAYcBAQAAAAGIAQEAAAABiQEBAAAAAYoBAQC7AQAhiwEBAAAAAYwBAQAAAAGNAQEAAAABC4MBAQAAAAGEAQEAAAAEhQEBAAAABIYBAQAAAAGHAQEAAAABiAEBAAAAAYkBAQAAAAGKAQEAvAEAIYsBAQAAAAGMAQEAAAABjQEBAAAAARADAADGAQAgBgAAwwEAIAcAAMQBACALAADFAQAgdQAAvQEAMHYAAAMAEHcAAL0BADB4AQC-AQAheQEAvgEAIXoBAL4BACF7AQC-AQAhfAEAvwEAIX4AAMABfiKAAQAAwQGAASKBAUAAwgEAIYIBQADCAQAhC4MBAQAAAAGEAQEAAAAEhQEBAAAABIYBAQAAAAGHAQEAAAABiAEBAAAAAYkBAQAAAAGKAQEAvAEAIYsBAQAAAAGMAQEAAAABjQEBAAAAAQuDAQEAAAABhAEBAAAABYUBAQAAAAWGAQEAAAABhwEBAAAAAYgBAQAAAAGJAQEAAAABigEBALoBACGLAQEAAAABjAEBAAAAAY0BAQAAAAEEgwEAAAB-AoQBAAAAfgiFAQAAAH4IigEAALcBfiIEgwEAAACAAQKEAQAAAIABCIUBAAAAgAEIigEAALUBgAEiCIMBQAAAAAGEAUAAAAAEhQFAAAAABIYBQAAAAAGHAUAAAAABiAFAAAAAAYkBQAAAAAGKAUAAswEAIQOOAQAABQAgjwEAAAUAIJABAAAFACADjgEAAAkAII8BAAAJACCQAQAACQAgA44BAAANACCPAQAADQAgkAEAAA0AIAOOAQAAGwAgjwEAABsAIJABAAAbACALdQAAxwEAMHYAAJABABB3AADHAQAweAEArAEAIYEBQACwAQAhggFAALABACGRAQIAyAEAIZIBAQCtAQAhkwEBAKwBACGUAQEArAEAIZUBAQCsAQAhDQoAALIBACAfAACyAQAgIAAAsgEAIDEAAMoBACAyAACyAQAggwECAAAAAYQBAgAAAASFAQIAAAAEhgECAAAAAYcBAgAAAAGIAQIAAAABiQECAAAAAYoBAgDJAQAhDQoAALIBACAfAACyAQAgIAAAsgEAIDEAAMoBACAyAACyAQAggwECAAAAAYQBAgAAAASFAQIAAAAEhgECAAAAAYcBAgAAAAGIAQIAAAABiQECAAAAAYoBAgDJAQAhCIMBCAAAAAGEAQgAAAAEhQEIAAAABIYBCAAAAAGHAQgAAAABiAEIAAAAAYkBCAAAAAGKAQgAygEAIQ11AADLAQAwdgAAegAQdwAAywEAMHgBAKwBACGAAQAAzQGbASKBAUAAsAEAIYIBQACwAQAhkwEBAKwBACGUAQEArAEAIZYBQACwAQAhlwFAALABACGYAQIAyAEAIZkBCADMAQAhDQoAALIBACAfAADKAQAgIAAAygEAIDEAAMoBACAyAADKAQAggwEIAAAAAYQBCAAAAASFAQgAAAAEhgEIAAAAAYcBCAAAAAGIAQgAAAABiQEIAAAAAYoBCADQAQAhBwoAALIBACAfAADPAQAgIAAAzwEAIIMBAAAAmwEChAEAAACbAQiFAQAAAJsBCIoBAADOAZsBIgcKAACyAQAgHwAAzwEAICAAAM8BACCDAQAAAJsBAoQBAAAAmwEIhQEAAACbAQiKAQAAzgGbASIEgwEAAACbAQKEAQAAAJsBCIUBAAAAmwEIigEAAM8BmwEiDQoAALIBACAfAADKAQAgIAAAygEAIDEAAMoBACAyAADKAQAggwEIAAAAAYQBCAAAAASFAQgAAAAEhgEIAAAAAYcBCAAAAAGIAQgAAAABiQEIAAAAAYoBCADQAQAhDHUAANEBADB2AABkABB3AADRAQAweAEArAEAIYABAADTAZ4BIoEBQACwAQAhggFAALABACGVAQEArAEAIZsBEADSAQAhnAEBAKwBACGeAQEArQEAIZ8BAQCtAQAhDQoAALIBACAfAADXAQAgIAAA1wEAIDEAANcBACAyAADXAQAggwEQAAAAAYQBEAAAAASFARAAAAAEhgEQAAAAAYcBEAAAAAGIARAAAAABiQEQAAAAAYoBEADWAQAhBwoAALIBACAfAADVAQAgIAAA1QEAIIMBAAAAngEChAEAAACeAQiFAQAAAJ4BCIoBAADUAZ4BIgcKAACyAQAgHwAA1QEAICAAANUBACCDAQAAAJ4BAoQBAAAAngEIhQEAAACeAQiKAQAA1AGeASIEgwEAAACeAQKEAQAAAJ4BCIUBAAAAngEIigEAANUBngEiDQoAALIBACAfAADXAQAgIAAA1wEAIDEAANcBACAyAADXAQAggwEQAAAAAYQBEAAAAASFARAAAAAEhgEQAAAAAYcBEAAAAAGIARAAAAABiQEQAAAAAYoBEADWAQAhCIMBEAAAAAGEARAAAAAEhQEQAAAABIYBEAAAAAGHARAAAAABiAEQAAAAAYkBEAAAAAGKARAA1wEAIQ91AADYAQAwdgAATgAQdwAA2AEAMHgBAKwBACGAAQAA2QGnASKBAUAAsAEAIYIBQACwAQAhoAEBAKwBACGhAQEArAEAIaIBAQCsAQAhowEIAMwBACGkAQIAyAEAIaUBAQCtAQAhpwEBAKwBACGoAQEArAEAIQcKAACyAQAgHwAA2wEAICAAANsBACCDAQAAAKcBAoQBAAAApwEIhQEAAACnAQiKAQAA2gGnASIHCgAAsgEAIB8AANsBACAgAADbAQAggwEAAACnAQKEAQAAAKcBCIUBAAAApwEIigEAANoBpwEiBIMBAAAApwEChAEAAACnAQiFAQAAAKcBCIoBAADbAacBIgh1AADcAQAwdgAAOAAQdwAA3AEAMHgBAKwBACF5AQCsAQAhgQFAALABACGCAUAAsAEAIakBAQCtAQAhCgYAAMMBACAMAADeAQAgdQAA3QEAMHYAABsAEHcAAN0BADB4AQC-AQAheQEAvgEAIYEBQADCAQAhggFAAMIBACGpAQEAvwEAIRIDAADGAQAgBgAAwwEAIAcAAMQBACALAADFAQAgdQAAvQEAMHYAAAMAEHcAAL0BADB4AQC-AQAheQEAvgEAIXoBAL4BACF7AQC-AQAhfAEAvwEAIX4AAMABfiKAAQAAwQGAASKBAUAAwgEAIYIBQADCAQAhqwEAAAMAIKwBAAADACAOBQAA4QEAIAYAAOIBACAHAADjAQAgdQAA3wEAMHYAAA0AEHcAAN8BADB4AQC-AQAhgQFAAMIBACGCAUAAwgEAIZEBAgDgAQAhkgEBAL8BACGTAQEAvgEAIZQBAQC-AQAhlQEBAL4BACEIgwECAAAAAYQBAgAAAASFAQIAAAAEhgECAAAAAYcBAgAAAAGIAQIAAAABiQECAAAAAYoBAgCyAQAhEgMAAMYBACAGAADDAQAgBwAAxAEAIAsAAMUBACB1AAC9AQAwdgAAAwAQdwAAvQEAMHgBAL4BACF5AQC-AQAhegEAvgEAIXsBAL4BACF8AQC_AQAhfgAAwAF-IoABAADBAYABIoEBQADCAQAhggFAAMIBACGrAQAAAwAgrAEAAAMAIBUDAADvAQAgBAAA4QEAIAcAAMQBACAIAADFAQAgdQAA7QEAMHYAAAUAEHcAAO0BADB4AQC-AQAhgAEAAO4BpwEigQFAAMIBACGCAUAAwgEAIaABAQC-AQAhoQEBAL4BACGiAQEAvgEAIaMBCADoAQAhpAECAOABACGlAQEAvwEAIacBAQC-AQAhqAEBAL4BACGrAQAABQAgrAEAAAUAIBMFAADhAQAgBgAA4gEAIAgAAOoBACAJAADrAQAgdQAA5wEAMHYAAAkAEHcAAOcBADB4AQC-AQAhgAEAAOkBmwEigQFAAMIBACGCAUAAwgEAIZMBAQC-AQAhlAEBAL4BACGWAUAAwgEAIZcBQADCAQAhmAECAOABACGZAQgA6AEAIasBAAAJACCsAQAACQAgDQcAAOMBACB1AADkAQAwdgAADwAQdwAA5AEAMHgBAL4BACGAAQAA5gGeASKBAUAAwgEAIYIBQADCAQAhlQEBAL4BACGbARAA5QEAIZwBAQC-AQAhngEBAL8BACGfAQEAvwEAIQiDARAAAAABhAEQAAAABIUBEAAAAASGARAAAAABhwEQAAAAAYgBEAAAAAGJARAAAAABigEQANcBACEEgwEAAACeAQKEAQAAAJ4BCIUBAAAAngEIigEAANUBngEiEQUAAOEBACAGAADiAQAgCAAA6gEAIAkAAOsBACB1AADnAQAwdgAACQAQdwAA5wEAMHgBAL4BACGAAQAA6QGbASKBAUAAwgEAIYIBQADCAQAhkwEBAL4BACGUAQEAvgEAIZYBQADCAQAhlwFAAMIBACGYAQIA4AEAIZkBCADoAQAhCIMBCAAAAAGEAQgAAAAEhQEIAAAABIYBCAAAAAGHAQgAAAABiAEIAAAAAYkBCAAAAAGKAQgAygEAIQSDAQAAAJsBAoQBAAAAmwEIhQEAAACbAQiKAQAAzwGbASIQBQAA4QEAIAYAAOIBACAHAADjAQAgdQAA3wEAMHYAAA0AEHcAAN8BADB4AQC-AQAhgQFAAMIBACGCAUAAwgEAIZEBAgDgAQAhkgEBAL8BACGTAQEAvgEAIZQBAQC-AQAhlQEBAL4BACGrAQAADQAgrAEAAA0AIAOOAQAADwAgjwEAAA8AIJABAAAPACADoAEBAAAAAaIBAQAAAAGoAQEAAAABEwMAAO8BACAEAADhAQAgBwAAxAEAIAgAAMUBACB1AADtAQAwdgAABQAQdwAA7QEAMHgBAL4BACGAAQAA7gGnASKBAUAAwgEAIYIBQADCAQAhoAEBAL4BACGhAQEAvgEAIaIBAQC-AQAhowEIAOgBACGkAQIA4AEAIaUBAQC_AQAhpwEBAL4BACGoAQEAvgEAIQSDAQAAAKcBAoQBAAAApwEIhQEAAACnAQiKAQAA2wGnASIMBgAAwwEAIAwAAN4BACB1AADdAQAwdgAAGwAQdwAA3QEAMHgBAL4BACF5AQC-AQAhgQFAAMIBACGCAUAAwgEAIakBAQC_AQAhqwEAABsAIKwBAAAbACAAAAAAAbABAQAAAAEBsAEBAAAAAQGwAQAAAH4CAbABAAAAgAECAbABQAAAAAELGQAA7AIAMBoAAPACADCtAQAA7QIAMK4BAADuAgAwrwEAAO8CACCwAQAAjQIAMLEBAACNAgAwsgEAAI0CADCzAQAAjQIAMLQBAADxAgAwtQEAAJACADALGQAA4QIAMBoAAOUCADCtAQAA4gIAMK4BAADjAgAwrwEAAOQCACCwAQAArgIAMLEBAACuAgAwsgEAAK4CADCzAQAArgIAMLQBAADmAgAwtQEAALECADALGQAA2AIAMBoAANwCADCtAQAA2QIAMK4BAADaAgAwrwEAANsCACCwAQAAngIAMLEBAACeAgAwsgEAAJ4CADCzAQAAngIAMLQBAADdAgAwtQEAAKECADALGQAA_QEAMBoAAIICADCtAQAA_gEAMK4BAAD_AQAwrwEAAIACACCwAQAAgQIAMLEBAACBAgAwsgEAAIECADCzAQAAgQIAMLQBAACDAgAwtQEAAIQCADAFBgAA1wIAIHgBAAAAAXkBAAAAAYEBQAAAAAGCAUAAAAABAgAAAAEAIBkAANYCACADAAAAAQAgGQAA1gIAIBoAAIcCACABEgAA1AMAMAoGAADDAQAgDAAA3gEAIHUAAN0BADB2AAAbABB3AADdAQAweAEAAAABeQEAAAABgQFAAMIBACGCAUAAwgEAIakBAQC_AQAhAgAAAAEAIBIAAIcCACACAAAAhQIAIBIAAIYCACAIdQAAhAIAMHYAAIUCABB3AACEAgAweAEAvgEAIXkBAL4BACGBAUAAwgEAIYIBQADCAQAhqQEBAL8BACEIdQAAhAIAMHYAAIUCABB3AACEAgAweAEAvgEAIXkBAL4BACGBAUAAwgEAIYIBQADCAQAhqQEBAL8BACEEeAEA9AEAIXkBAPQBACGBAUAA-AEAIYIBQAD4AQAhBQYAAIgCACB4AQD0AQAheQEA9AEAIYEBQAD4AQAhggFAAPgBACELGQAAiQIAMBoAAI4CADCtAQAAigIAMK4BAACLAgAwrwEAAIwCACCwAQAAjQIAMLEBAACNAgAwsgEAAI0CADCzAQAAjQIAMLQBAACPAgAwtQEAAJACADAOBAAA0wIAIAcAANQCACAIAADVAgAgeAEAAAABgAEAAACnAQKBAUAAAAABggFAAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBCAAAAAGkAQIAAAABpQEBAAAAAagBAQAAAAECAAAABwAgGQAA0gIAIAMAAAAHACAZAADSAgAgGgAAlgIAIAESAADTAwAwFAMAAO8BACAEAADhAQAgBwAAxAEAIAgAAMUBACB1AADtAQAwdgAABQAQdwAA7QEAMHgBAAAAAYABAADuAacBIoEBQADCAQAhggFAAMIBACGgAQEAvgEAIaEBAQC-AQAhogEBAL4BACGjAQgA6AEAIaQBAgDgAQAhpQEBAL8BACGnAQEAvgEAIagBAQC-AQAhqgEAAOwBACACAAAABwAgEgAAlgIAIAIAAACRAgAgEgAAkgIAIA91AACQAgAwdgAAkQIAEHcAAJACADB4AQC-AQAhgAEAAO4BpwEigQFAAMIBACGCAUAAwgEAIaABAQC-AQAhoQEBAL4BACGiAQEAvgEAIaMBCADoAQAhpAECAOABACGlAQEAvwEAIacBAQC-AQAhqAEBAL4BACEPdQAAkAIAMHYAAJECABB3AACQAgAweAEAvgEAIYABAADuAacBIoEBQADCAQAhggFAAMIBACGgAQEAvgEAIaEBAQC-AQAhogEBAL4BACGjAQgA6AEAIaQBAgDgAQAhpQEBAL8BACGnAQEAvgEAIagBAQC-AQAhC3gBAPQBACGAAQAAlQKnASKBAUAA-AEAIYIBQAD4AQAhoAEBAPQBACGhAQEA9AEAIaIBAQD0AQAhowEIAJMCACGkAQIAlAIAIaUBAQD1AQAhqAEBAPQBACEFsAEIAAAAAbYBCAAAAAG3AQgAAAABuAEIAAAAAbkBCAAAAAEFsAECAAAAAbYBAgAAAAG3AQIAAAABuAECAAAAAbkBAgAAAAEBsAEAAACnAQIOBAAAlwIAIAcAAJgCACAIAACZAgAgeAEA9AEAIYABAACVAqcBIoEBQAD4AQAhggFAAPgBACGgAQEA9AEAIaEBAQD0AQAhogEBAPQBACGjAQgAkwIAIaQBAgCUAgAhpQEBAPUBACGoAQEA9AEAIQUZAAC3AwAgGgAA0QMAIK0BAAC4AwAgrgEAANADACCzAQAAkwEAIAsZAACqAgAwGgAArwIAMK0BAACrAgAwrgEAAKwCADCvAQAArQIAILABAACuAgAwsQEAAK4CADCyAQAArgIAMLMBAACuAgAwtAEAALACADC1AQAAsQIAMAsZAACaAgAwGgAAnwIAMK0BAACbAgAwrgEAAJwCADCvAQAAnQIAILABAACeAgAwsQEAAJ4CADCyAQAAngIAMLMBAACeAgAwtAEAAKACADC1AQAAoQIAMAkFAACoAgAgBwAAqQIAIHgBAAAAAYEBQAAAAAGCAUAAAAABkQECAAAAAZIBAQAAAAGTAQEAAAABlQEBAAAAAQIAAAAVACAZAACnAgAgAwAAABUAIBkAAKcCACAaAACkAgAgARIAAM8DADAOBQAA4QEAIAYAAOIBACAHAADjAQAgdQAA3wEAMHYAAA0AEHcAAN8BADB4AQAAAAGBAUAAwgEAIYIBQADCAQAhkQECAOABACGSAQEAvwEAIZMBAQC-AQAhlAEBAL4BACGVAQEAAAABAgAAABUAIBIAAKQCACACAAAAogIAIBIAAKMCACALdQAAoQIAMHYAAKICABB3AAChAgAweAEAvgEAIYEBQADCAQAhggFAAMIBACGRAQIA4AEAIZIBAQC_AQAhkwEBAL4BACGUAQEAvgEAIZUBAQC-AQAhC3UAAKECADB2AACiAgAQdwAAoQIAMHgBAL4BACGBAUAAwgEAIYIBQADCAQAhkQECAOABACGSAQEAvwEAIZMBAQC-AQAhlAEBAL4BACGVAQEAvgEAIQd4AQD0AQAhgQFAAPgBACGCAUAA-AEAIZEBAgCUAgAhkgEBAPUBACGTAQEA9AEAIZUBAQD0AQAhCQUAAKUCACAHAACmAgAgeAEA9AEAIYEBQAD4AQAhggFAAPgBACGRAQIAlAIAIZIBAQD1AQAhkwEBAPQBACGVAQEA9AEAIQUZAADHAwAgGgAAzQMAIK0BAADIAwAgrgEAAMwDACCzAQAAkwEAIAUZAADFAwAgGgAAygMAIK0BAADGAwAgrgEAAMkDACCzAQAACwAgCQUAAKgCACAHAACpAgAgeAEAAAABgQFAAAAAAYIBQAAAAAGRAQIAAAABkgEBAAAAAZMBAQAAAAGVAQEAAAABAxkAAMcDACCtAQAAyAMAILMBAACTAQAgAxkAAMUDACCtAQAAxgMAILMBAAALACAMBQAAzwIAIAgAANACACAJAADRAgAgeAEAAAABgAEAAACbAQKBAUAAAAABggFAAAAAAZMBAQAAAAGWAUAAAAABlwFAAAAAAZgBAgAAAAGZAQgAAAABAgAAAAsAIBkAAM4CACADAAAACwAgGQAAzgIAIBoAALUCACABEgAAxAMAMBEFAADhAQAgBgAA4gEAIAgAAOoBACAJAADrAQAgdQAA5wEAMHYAAAkAEHcAAOcBADB4AQAAAAGAAQAA6QGbASKBAUAAwgEAIYIBQADCAQAhkwEBAL4BACGUAQEAvgEAIZYBQADCAQAhlwFAAMIBACGYAQIA4AEAIZkBCADoAQAhAgAAAAsAIBIAALUCACACAAAAsgIAIBIAALMCACANdQAAsQIAMHYAALICABB3AACxAgAweAEAvgEAIYABAADpAZsBIoEBQADCAQAhggFAAMIBACGTAQEAvgEAIZQBAQC-AQAhlgFAAMIBACGXAUAAwgEAIZgBAgDgAQAhmQEIAOgBACENdQAAsQIAMHYAALICABB3AACxAgAweAEAvgEAIYABAADpAZsBIoEBQADCAQAhggFAAMIBACGTAQEAvgEAIZQBAQC-AQAhlgFAAMIBACGXAUAAwgEAIZgBAgDgAQAhmQEIAOgBACEJeAEA9AEAIYABAAC0ApsBIoEBQAD4AQAhggFAAPgBACGTAQEA9AEAIZYBQAD4AQAhlwFAAPgBACGYAQIAlAIAIZkBCACTAgAhAbABAAAAmwECDAUAALYCACAIAAC3AgAgCQAAuAIAIHgBAPQBACGAAQAAtAKbASKBAUAA-AEAIYIBQAD4AQAhkwEBAPQBACGWAUAA-AEAIZcBQAD4AQAhmAECAJQCACGZAQgAkwIAIQUZAAC5AwAgGgAAwgMAIK0BAAC6AwAgrgEAAMEDACCzAQAAkwEAIAcZAADHAgAgGgAAygIAIK0BAADIAgAgrgEAAMkCACCxAQAADQAgsgEAAA0AILMBAAAVACALGQAAuQIAMBoAAL4CADCtAQAAugIAMK4BAAC7AgAwrwEAALwCACCwAQAAvQIAMLEBAAC9AgAwsgEAAL0CADCzAQAAvQIAMLQBAAC_AgAwtQEAAMACADAIeAEAAAABgAEAAACeAQKBAUAAAAABggFAAAAAAZsBEAAAAAGcAQEAAAABngEBAAAAAZ8BAQAAAAECAAAAEQAgGQAAxgIAIAMAAAARACAZAADGAgAgGgAAxQIAIAESAADAAwAwDQcAAOMBACB1AADkAQAwdgAADwAQdwAA5AEAMHgBAAAAAYABAADmAZ4BIoEBQADCAQAhggFAAMIBACGVAQEAAAABmwEQAOUBACGcAQEAvgEAIZ4BAQAAAAGfAQEAvwEAIQIAAAARACASAADFAgAgAgAAAMECACASAADCAgAgDHUAAMACADB2AADBAgAQdwAAwAIAMHgBAL4BACGAAQAA5gGeASKBAUAAwgEAIYIBQADCAQAhlQEBAL4BACGbARAA5QEAIZwBAQC-AQAhngEBAL8BACGfAQEAvwEAIQx1AADAAgAwdgAAwQIAEHcAAMACADB4AQC-AQAhgAEAAOYBngEigQFAAMIBACGCAUAAwgEAIZUBAQC-AQAhmwEQAOUBACGcAQEAvgEAIZ4BAQC_AQAhnwEBAL8BACEIeAEA9AEAIYABAADEAp4BIoEBQAD4AQAhggFAAPgBACGbARAAwwIAIZwBAQD0AQAhngEBAPUBACGfAQEA9QEAIQWwARAAAAABtgEQAAAAAbcBEAAAAAG4ARAAAAABuQEQAAAAAQGwAQAAAJ4BAgh4AQD0AQAhgAEAAMQCngEigQFAAPgBACGCAUAA-AEAIZsBEADDAgAhnAEBAPQBACGeAQEA9QEAIZ8BAQD1AQAhCHgBAAAAAYABAAAAngECgQFAAAAAAYIBQAAAAAGbARAAAAABnAEBAAAAAZ4BAQAAAAGfAQEAAAABCQUAAKgCACAGAADNAgAgeAEAAAABgQFAAAAAAYIBQAAAAAGRAQIAAAABkgEBAAAAAZMBAQAAAAGUAQEAAAABAgAAABUAIBkAAMcCACADAAAADQAgGQAAxwIAIBoAAMsCACALAAAADQAgBQAApQIAIAYAAMwCACASAADLAgAgeAEA9AEAIYEBQAD4AQAhggFAAPgBACGRAQIAlAIAIZIBAQD1AQAhkwEBAPQBACGUAQEA9AEAIQkFAAClAgAgBgAAzAIAIHgBAPQBACGBAUAA-AEAIYIBQAD4AQAhkQECAJQCACGSAQEA9QEAIZMBAQD0AQAhlAEBAPQBACEFGQAAuwMAIBoAAL4DACCtAQAAvAMAIK4BAAC9AwAgswEAAAcAIAMZAAC7AwAgrQEAALwDACCzAQAABwAgDAUAAM8CACAIAADQAgAgCQAA0QIAIHgBAAAAAYABAAAAmwECgQFAAAAAAYIBQAAAAAGTAQEAAAABlgFAAAAAAZcBQAAAAAGYAQIAAAABmQEIAAAAAQMZAAC5AwAgrQEAALoDACCzAQAAkwEAIAMZAADHAgAgrQEAAMgCACCzAQAAFQAgBBkAALkCADCtAQAAugIAMK8BAAC8AgAgswEAAL0CADAOBAAA0wIAIAcAANQCACAIAADVAgAgeAEAAAABgAEAAACnAQKBAUAAAAABggFAAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBCAAAAAGkAQIAAAABpQEBAAAAAagBAQAAAAEDGQAAtwMAIK0BAAC4AwAgswEAAJMBACAEGQAAqgIAMK0BAACrAgAwrwEAAK0CACCzAQAArgIAMAQZAACaAgAwrQEAAJsCADCvAQAAnQIAILMBAACeAgAwBQYAANcCACB4AQAAAAF5AQAAAAGBAUAAAAABggFAAAAAAQQZAACJAgAwrQEAAIoCADCvAQAAjAIAILMBAACNAgAwCQYAAM0CACAHAACpAgAgeAEAAAABgQFAAAAAAYIBQAAAAAGRAQIAAAABkgEBAAAAAZQBAQAAAAGVAQEAAAABAgAAABUAIBkAAOACACADAAAAFQAgGQAA4AIAIBoAAN8CACABEgAAtgMAMAIAAAAVACASAADfAgAgAgAAAKICACASAADeAgAgB3gBAPQBACGBAUAA-AEAIYIBQAD4AQAhkQECAJQCACGSAQEA9QEAIZQBAQD0AQAhlQEBAPQBACEJBgAAzAIAIAcAAKYCACB4AQD0AQAhgQFAAPgBACGCAUAA-AEAIZEBAgCUAgAhkgEBAPUBACGUAQEA9AEAIZUBAQD0AQAhCQYAAM0CACAHAACpAgAgeAEAAAABgQFAAAAAAYIBQAAAAAGRAQIAAAABkgEBAAAAAZQBAQAAAAGVAQEAAAABDAYAAOsCACAIAADQAgAgCQAA0QIAIHgBAAAAAYABAAAAmwECgQFAAAAAAYIBQAAAAAGUAQEAAAABlgFAAAAAAZcBQAAAAAGYAQIAAAABmQEIAAAAAQIAAAALACAZAADqAgAgAwAAAAsAIBkAAOoCACAaAADoAgAgARIAALUDADACAAAACwAgEgAA6AIAIAIAAACyAgAgEgAA5wIAIAl4AQD0AQAhgAEAALQCmwEigQFAAPgBACGCAUAA-AEAIZQBAQD0AQAhlgFAAPgBACGXAUAA-AEAIZgBAgCUAgAhmQEIAJMCACEMBgAA6QIAIAgAALcCACAJAAC4AgAgeAEA9AEAIYABAAC0ApsBIoEBQAD4AQAhggFAAPgBACGUAQEA9AEAIZYBQAD4AQAhlwFAAPgBACGYAQIAlAIAIZkBCACTAgAhBRkAALADACAaAACzAwAgrQEAALEDACCuAQAAsgMAILMBAAAHACAMBgAA6wIAIAgAANACACAJAADRAgAgeAEAAAABgAEAAACbAQKBAUAAAAABggFAAAAAAZQBAQAAAAGWAUAAAAABlwFAAAAAAZgBAgAAAAGZAQgAAAABAxkAALADACCtAQAAsQMAILMBAAAHACAOAwAA9gIAIAcAANQCACAIAADVAgAgeAEAAAABgAEAAACnAQKBAUAAAAABggFAAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBCAAAAAGkAQIAAAABpQEBAAAAAacBAQAAAAECAAAABwAgGQAA9QIAIAMAAAAHACAZAAD1AgAgGgAA8wIAIAESAACvAwAwAgAAAAcAIBIAAPMCACACAAAAkQIAIBIAAPICACALeAEA9AEAIYABAACVAqcBIoEBQAD4AQAhggFAAPgBACGgAQEA9AEAIaEBAQD0AQAhogEBAPQBACGjAQgAkwIAIaQBAgCUAgAhpQEBAPUBACGnAQEA9AEAIQ4DAAD0AgAgBwAAmAIAIAgAAJkCACB4AQD0AQAhgAEAAJUCpwEigQFAAPgBACGCAUAA-AEAIaABAQD0AQAhoQEBAPQBACGiAQEA9AEAIaMBCACTAgAhpAECAJQCACGlAQEA9QEAIacBAQD0AQAhBRkAAKoDACAaAACtAwAgrQEAAKsDACCuAQAArAMAILMBAAABACAOAwAA9gIAIAcAANQCACAIAADVAgAgeAEAAAABgAEAAACnAQKBAUAAAAABggFAAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBCAAAAAGkAQIAAAABpQEBAAAAAacBAQAAAAEDGQAAqgMAIK0BAACrAwAgswEAAAEAIAQZAADsAgAwrQEAAO0CADCvAQAA7wIAILMBAACNAgAwBBkAAOECADCtAQAA4gIAMK8BAADkAgAgswEAAK4CADAEGQAA2AIAMK0BAADZAgAwrwEAANsCACCzAQAAngIAMAQZAAD9AQAwrQEAAP4BADCvAQAAgAIAILMBAACBAgAwAAAAAAAAAAAAAAAAAAAAAAAAAAUZAAClAwAgGgAAqAMAIK0BAACmAwAgrgEAAKcDACCzAQAACwAgAxkAAKUDACCtAQAApgMAILMBAAALACAAAAAAAAAAAAcZAACgAwAgGgAAowMAIK0BAAChAwAgrgEAAKIDACCxAQAAAwAgsgEAAAMAILMBAACTAQAgAxkAAKADACCtAQAAoQMAILMBAACTAQAgBQMAAP4CACAGAAD7AgAgBwAA_AIAIAsAAP0CACB8AADwAQAgBQMAAJ8DACAEAACaAwAgBwAA_AIAIAgAAP0CACClAQAA8AEAIAQFAACaAwAgBgAAmwMAIAgAAJ0DACAJAACeAwAgBAUAAJoDACAGAACbAwAgBwAAnAMAIJIBAADwAQAgAAMGAAD7AgAgDAAAmgMAIKkBAADwAQAgDAYAAPcCACAHAAD4AgAgCwAA-QIAIHgBAAAAAXkBAAAAAXoBAAAAAXsBAAAAAXwBAAAAAX4AAAB-AoABAAAAgAECgQFAAAAAAYIBQAAAAAECAAAAkwEAIBkAAKADACADAAAAAwAgGQAAoAMAIBoAAKQDACAOAAAAAwAgBgAA-QEAIAcAAPoBACALAAD7AQAgEgAApAMAIHgBAPQBACF5AQD0AQAhegEA9AEAIXsBAPQBACF8AQD1AQAhfgAA9gF-IoABAAD3AYABIoEBQAD4AQAhggFAAPgBACEMBgAA-QEAIAcAAPoBACALAAD7AQAgeAEA9AEAIXkBAPQBACF6AQD0AQAhewEA9AEAIXwBAPUBACF-AAD2AX4igAEAAPcBgAEigQFAAPgBACGCAUAA-AEAIQ0FAADPAgAgBgAA6wIAIAgAANACACB4AQAAAAGAAQAAAJsBAoEBQAAAAAGCAUAAAAABkwEBAAAAAZQBAQAAAAGWAUAAAAABlwFAAAAAAZgBAgAAAAGZAQgAAAABAgAAAAsAIBkAAKUDACADAAAACQAgGQAApQMAIBoAAKkDACAPAAAACQAgBQAAtgIAIAYAAOkCACAIAAC3AgAgEgAAqQMAIHgBAPQBACGAAQAAtAKbASKBAUAA-AEAIYIBQAD4AQAhkwEBAPQBACGUAQEA9AEAIZYBQAD4AQAhlwFAAPgBACGYAQIAlAIAIZkBCACTAgAhDQUAALYCACAGAADpAgAgCAAAtwIAIHgBAPQBACGAAQAAtAKbASKBAUAA-AEAIYIBQAD4AQAhkwEBAPQBACGUAQEA9AEAIZYBQAD4AQAhlwFAAPgBACGYAQIAlAIAIZkBCACTAgAhBgwAAJkDACB4AQAAAAF5AQAAAAGBAUAAAAABggFAAAAAAakBAQAAAAECAAAAAQAgGQAAqgMAIAMAAAAbACAZAACqAwAgGgAArgMAIAgAAAAbACAMAACYAwAgEgAArgMAIHgBAPQBACF5AQD0AQAhgQFAAPgBACGCAUAA-AEAIakBAQD1AQAhBgwAAJgDACB4AQD0AQAheQEA9AEAIYEBQAD4AQAhggFAAPgBACGpAQEA9QEAIQt4AQAAAAGAAQAAAKcBAoEBQAAAAAGCAUAAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEIAAAAAaQBAgAAAAGlAQEAAAABpwEBAAAAAQ8DAAD2AgAgBAAA0wIAIAgAANUCACB4AQAAAAGAAQAAAKcBAoEBQAAAAAGCAUAAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEIAAAAAaQBAgAAAAGlAQEAAAABpwEBAAAAAagBAQAAAAECAAAABwAgGQAAsAMAIAMAAAAFACAZAACwAwAgGgAAtAMAIBEAAAAFACADAAD0AgAgBAAAlwIAIAgAAJkCACASAAC0AwAgeAEA9AEAIYABAACVAqcBIoEBQAD4AQAhggFAAPgBACGgAQEA9AEAIaEBAQD0AQAhogEBAPQBACGjAQgAkwIAIaQBAgCUAgAhpQEBAPUBACGnAQEA9AEAIagBAQD0AQAhDwMAAPQCACAEAACXAgAgCAAAmQIAIHgBAPQBACGAAQAAlQKnASKBAUAA-AEAIYIBQAD4AQAhoAEBAPQBACGhAQEA9AEAIaIBAQD0AQAhowEIAJMCACGkAQIAlAIAIaUBAQD1AQAhpwEBAPQBACGoAQEA9AEAIQl4AQAAAAGAAQAAAJsBAoEBQAAAAAGCAUAAAAABlAEBAAAAAZYBQAAAAAGXAUAAAAABmAECAAAAAZkBCAAAAAEHeAEAAAABgQFAAAAAAYIBQAAAAAGRAQIAAAABkgEBAAAAAZQBAQAAAAGVAQEAAAABDAMAAPoCACAHAAD4AgAgCwAA-QIAIHgBAAAAAXkBAAAAAXoBAAAAAXsBAAAAAXwBAAAAAX4AAAB-AoABAAAAgAECgQFAAAAAAYIBQAAAAAECAAAAkwEAIBkAALcDACAMAwAA-gIAIAYAAPcCACALAAD5AgAgeAEAAAABeQEAAAABegEAAAABewEAAAABfAEAAAABfgAAAH4CgAEAAACAAQKBAUAAAAABggFAAAAAAQIAAACTAQAgGQAAuQMAIA8DAAD2AgAgBAAA0wIAIAcAANQCACB4AQAAAAGAAQAAAKcBAoEBQAAAAAGCAUAAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEIAAAAAaQBAgAAAAGlAQEAAAABpwEBAAAAAagBAQAAAAECAAAABwAgGQAAuwMAIAMAAAAFACAZAAC7AwAgGgAAvwMAIBEAAAAFACADAAD0AgAgBAAAlwIAIAcAAJgCACASAAC_AwAgeAEA9AEAIYABAACVAqcBIoEBQAD4AQAhggFAAPgBACGgAQEA9AEAIaEBAQD0AQAhogEBAPQBACGjAQgAkwIAIaQBAgCUAgAhpQEBAPUBACGnAQEA9AEAIagBAQD0AQAhDwMAAPQCACAEAACXAgAgBwAAmAIAIHgBAPQBACGAAQAAlQKnASKBAUAA-AEAIYIBQAD4AQAhoAEBAPQBACGhAQEA9AEAIaIBAQD0AQAhowEIAJMCACGkAQIAlAIAIaUBAQD1AQAhpwEBAPQBACGoAQEA9AEAIQh4AQAAAAGAAQAAAJ4BAoEBQAAAAAGCAUAAAAABmwEQAAAAAZwBAQAAAAGeAQEAAAABnwEBAAAAAQMAAAADACAZAAC5AwAgGgAAwwMAIA4AAAADACADAAD8AQAgBgAA-QEAIAsAAPsBACASAADDAwAgeAEA9AEAIXkBAPQBACF6AQD0AQAhewEA9AEAIXwBAPUBACF-AAD2AX4igAEAAPcBgAEigQFAAPgBACGCAUAA-AEAIQwDAAD8AQAgBgAA-QEAIAsAAPsBACB4AQD0AQAheQEA9AEAIXoBAPQBACF7AQD0AQAhfAEA9QEAIX4AAPYBfiKAAQAA9wGAASKBAUAA-AEAIYIBQAD4AQAhCXgBAAAAAYABAAAAmwECgQFAAAAAAYIBQAAAAAGTAQEAAAABlgFAAAAAAZcBQAAAAAGYAQIAAAABmQEIAAAAAQ0FAADPAgAgBgAA6wIAIAkAANECACB4AQAAAAGAAQAAAJsBAoEBQAAAAAGCAUAAAAABkwEBAAAAAZQBAQAAAAGWAUAAAAABlwFAAAAAAZgBAgAAAAGZAQgAAAABAgAAAAsAIBkAAMUDACAMAwAA-gIAIAYAAPcCACAHAAD4AgAgeAEAAAABeQEAAAABegEAAAABewEAAAABfAEAAAABfgAAAH4CgAEAAACAAQKBAUAAAAABggFAAAAAAQIAAACTAQAgGQAAxwMAIAMAAAAJACAZAADFAwAgGgAAywMAIA8AAAAJACAFAAC2AgAgBgAA6QIAIAkAALgCACASAADLAwAgeAEA9AEAIYABAAC0ApsBIoEBQAD4AQAhggFAAPgBACGTAQEA9AEAIZQBAQD0AQAhlgFAAPgBACGXAUAA-AEAIZgBAgCUAgAhmQEIAJMCACENBQAAtgIAIAYAAOkCACAJAAC4AgAgeAEA9AEAIYABAAC0ApsBIoEBQAD4AQAhggFAAPgBACGTAQEA9AEAIZQBAQD0AQAhlgFAAPgBACGXAUAA-AEAIZgBAgCUAgAhmQEIAJMCACEDAAAAAwAgGQAAxwMAIBoAAM4DACAOAAAAAwAgAwAA_AEAIAYAAPkBACAHAAD6AQAgEgAAzgMAIHgBAPQBACF5AQD0AQAhegEA9AEAIXsBAPQBACF8AQD1AQAhfgAA9gF-IoABAAD3AYABIoEBQAD4AQAhggFAAPgBACEMAwAA_AEAIAYAAPkBACAHAAD6AQAgeAEA9AEAIXkBAPQBACF6AQD0AQAhewEA9AEAIXwBAPUBACF-AAD2AX4igAEAAPcBgAEigQFAAPgBACGCAUAA-AEAIQd4AQAAAAGBAUAAAAABggFAAAAAAZEBAgAAAAGSAQEAAAABkwEBAAAAAZUBAQAAAAEDAAAAAwAgGQAAtwMAIBoAANIDACAOAAAAAwAgAwAA_AEAIAcAAPoBACALAAD7AQAgEgAA0gMAIHgBAPQBACF5AQD0AQAhegEA9AEAIXsBAPQBACF8AQD1AQAhfgAA9gF-IoABAAD3AYABIoEBQAD4AQAhggFAAPgBACEMAwAA_AEAIAcAAPoBACALAAD7AQAgeAEA9AEAIXkBAPQBACF6AQD0AQAhewEA9AEAIXwBAPUBACF-AAD2AX4igAEAAPcBgAEigQFAAPgBACGCAUAA-AEAIQt4AQAAAAGAAQAAAKcBAoEBQAAAAAGCAUAAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEIAAAAAaQBAgAAAAGlAQEAAAABqAEBAAAAAQR4AQAAAAF5AQAAAAGBAUAAAAABggFAAAAAAQMGIgMKAAoMBAIFAx0BBggDBxkECgAJCxoFBQMAAQQAAgcMBAgWBQoACAUFAAIGAAMIDgUJEgYKAAcDBQACBgADBwAEAQcABAEJEwACBxcACBgABAMhAAYeAAcfAAsgAAEGIwAAAQwtAgEMMwIDCgAPHwAQIAARAAAAAwoADx8AECAAEQIDAAEEAAICAwABBAACBQoAFh8AGSAAGjEAFzIAGAAAAAAABQoAFh8AGSAAGjEAFzIAGAEHAAQBBwAEBQoAHx8AIiAAIzEAIDIAIQAAAAAABQoAHx8AIiAAIzEAIDIAIQIFAAIGAAMCBQACBgADBQoAKB8AKyAALDEAKTIAKgAAAAAABQoAKB8AKyAALDEAKTIAKgMFAAIGAAMHAAQDBQACBgADBwAEBQoAMR8ANCAANTEAMjIAMwAAAAAABQoAMR8ANCAANTEAMjIAMwAAAwoAOh8AOyAAPAAAAAMKADofADsgADwNAgEOJAEPJQEQJgERJwETKQEUKwsVLAwWLwEXMQsYMg0bNAEcNQEdNgshOQ4iOhIjOwMkPAMlPQMmPgMnPwMoQQMpQwsqRBMrRgMsSAstSRQuSgMvSwMwTAszTxU0UBs1UQY2UgY3UwY4VAY5VQY6VwY7WQs8Whw9XAY-Xgs_Xx1AYAZBYQZCYgtDZR5EZiRFZwRGaARHaQRIagRJawRKbQRLbwtMcCVNcgROdAtPdSZQdgRRdwRSeAtTeydUfC1VfQVWfgVXfwVYgAEFWYEBBVqDAQVbhQELXIYBLl2IAQVeigELX4sBL2CMAQVhjQEFYo4BC2ORATBkkgE2ZZQBAmaVAQJnlwECaJgBAmmZAQJqmwECa50BC2yeATdtoAECbqIBC2-jAThwpAECcaUBAnKmAQtzqQE5dKoBPQ"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer: Buffer2 } = await import("buffer");
  const wasmArray = Buffer2.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
var prismaNamespace_exports = {};
__export(prismaNamespace_exports, {
  AnyNull: () => AnyNull2,
  CategoryScalarFieldEnum: () => CategoryScalarFieldEnum,
  DbNull: () => DbNull2,
  Decimal: () => Decimal2,
  GearScalarFieldEnum: () => GearScalarFieldEnum,
  JsonNull: () => JsonNull2,
  ModelName: () => ModelName,
  NullTypes: () => NullTypes2,
  NullsOrder: () => NullsOrder,
  PaymentScalarFieldEnum: () => PaymentScalarFieldEnum,
  PrismaClientInitializationError: () => PrismaClientInitializationError2,
  PrismaClientKnownRequestError: () => PrismaClientKnownRequestError2,
  PrismaClientRustPanicError: () => PrismaClientRustPanicError2,
  PrismaClientUnknownRequestError: () => PrismaClientUnknownRequestError2,
  PrismaClientValidationError: () => PrismaClientValidationError2,
  QueryMode: () => QueryMode,
  RentalScalarFieldEnum: () => RentalScalarFieldEnum,
  ReviewScalarFieldEnum: () => ReviewScalarFieldEnum,
  SortOrder: () => SortOrder,
  Sql: () => Sql2,
  TransactionIsolationLevel: () => TransactionIsolationLevel,
  UserScalarFieldEnum: () => UserScalarFieldEnum,
  defineExtension: () => defineExtension,
  empty: () => empty2,
  getExtensionContext: () => getExtensionContext,
  join: () => join2,
  prismaVersion: () => prismaVersion,
  raw: () => raw2,
  sql: () => sql
});
import * as runtime2 from "@prisma/client/runtime/client";
var PrismaClientKnownRequestError2 = runtime2.PrismaClientKnownRequestError;
var PrismaClientUnknownRequestError2 = runtime2.PrismaClientUnknownRequestError;
var PrismaClientRustPanicError2 = runtime2.PrismaClientRustPanicError;
var PrismaClientInitializationError2 = runtime2.PrismaClientInitializationError;
var PrismaClientValidationError2 = runtime2.PrismaClientValidationError;
var sql = runtime2.sqltag;
var empty2 = runtime2.empty;
var join2 = runtime2.join;
var raw2 = runtime2.raw;
var Sql2 = runtime2.Sql;
var Decimal2 = runtime2.Decimal;
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
};
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var DbNull2 = runtime2.DbNull;
var JsonNull2 = runtime2.JsonNull;
var AnyNull2 = runtime2.AnyNull;
var ModelName = {
  Category: "Category",
  Gear: "Gear",
  Payment: "Payment",
  Rental: "Rental",
  Review: "Review",
  User: "User"
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var CategoryScalarFieldEnum = {
  id: "id",
  name: "name",
  createdBy: "createdBy",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var GearScalarFieldEnum = {
  id: "id",
  title: "title",
  description: "description",
  brand: "brand",
  pricePerDay: "pricePerDay",
  quantity: "quantity",
  image: "image",
  status: "status",
  categoryId: "categoryId",
  providerId: "providerId",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var PaymentScalarFieldEnum = {
  id: "id",
  amount: "amount",
  currency: "currency",
  status: "status",
  transactionId: "transactionId",
  paymentMethod: "paymentMethod",
  rentalId: "rentalId",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var RentalScalarFieldEnum = {
  id: "id",
  startDate: "startDate",
  endDate: "endDate",
  totalDays: "totalDays",
  totalPrice: "totalPrice",
  status: "status",
  customerId: "customerId",
  gearId: "gearId",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var ReviewScalarFieldEnum = {
  id: "id",
  rating: "rating",
  comment: "comment",
  customerId: "customerId",
  gearId: "gearId",
  rentalId: "rentalId",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var UserScalarFieldEnum = {
  id: "id",
  name: "name",
  password: "password",
  email: "email",
  photoUrl: "photoUrl",
  role: "role",
  status: "status",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var SortOrder = {
  asc: "asc",
  desc: "desc"
};
var QueryMode = {
  default: "default",
  insensitive: "insensitive"
};
var NullsOrder = {
  first: "first",
  last: "last"
};
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var UserRole = {
  ADMIN: "ADMIN",
  PROVIDER: "PROVIDER",
  CUSTOMER: "CUSTOMER"
};
var GearStatus = {
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE: "UNAVAILABLE"
};
var RentalStatus = {
  PLACED: "PLACED",
  CONFIRMED: "CONFIRMED",
  PAID: "PAID",
  PICKED_UP: "PICKED_UP",
  RETURNED: "RETURNED",
  CANCELLED: "CANCELLED"
};

// generated/prisma/client.ts
globalThis["__dirname"] = path2.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// utiles/jwt.ts
import jwt from "jsonwebtoken";
var createToken = (payload, secret, expiresIn) => {
  const token = jwt.sign(payload, secret, expiresIn);
  return token;
};
var verifyToken = (token, secret) => {
  try {
    const verifyToken2 = jwt.verify(token, secret);
    return {
      success: true,
      data: verifyToken2
    };
  } catch (error) {
    return {
      success: false,
      error: error.message
    };
  }
};
var jwtUtils = {
  createToken,
  verifyToken
};

// src/modular/auth/auth.service.ts
var createUserIntoDB = async (payload) => {
  const { name, email, password, role, photoUrl } = payload;
  const isExist = await prisma.user.findUnique({
    where: {
      email
    }
  });
  if (isExist) {
    throw new Error("User already Exist");
  }
  const hashPassword = await bcrypt.hash(
    password,
    Number(config_default.bcrypt_hash_pass)
  );
  const createUser2 = await prisma.user.create({
    data: {
      name,
      email,
      password: hashPassword,
      role,
      photoUrl
    },
    omit: {
      password: true
    }
  });
  const user = await prisma.user.findUnique({
    where: {
      id: createUser2.id,
      email: createUser2.email
    },
    omit: {
      password: true
    }
  });
  return user;
};
var loginUser = async (payload) => {
  const { email, password } = payload;
  const matchUser = await prisma.user.findUniqueOrThrow({
    where: {
      email
    }
  });
  if (matchUser.status === "BLOCKED") {
    throw new Error("User account Blocked");
  }
  const matchPassword = await bcrypt.compare(password, matchUser.password);
  if (!matchPassword) {
    throw new Error("Password incorrect");
  }
  const jwtPayload = {
    id: matchUser.id,
    name: matchUser.name,
    email: matchUser.email,
    role: matchUser.role
  };
  const accessToken = jwtUtils.createToken(
    jwtPayload,
    config_default.access_token_secret_key,
    { expiresIn: config_default.access_token_expire_in }
  );
  const refreshToken3 = jwtUtils.createToken(
    jwtPayload,
    config_default.refresh_token_secret_key,
    { expiresIn: config_default.refresh_token_expire_in }
  );
  return {
    accessToken,
    refreshToken: refreshToken3
  };
};
var getMyProfile = async (userId) => {
  const user = await prisma.user.findUniqueOrThrow({
    where: {
      id: userId
    },
    omit: {
      password: true
    }
  });
  return user;
};
var refreshToken = async (refreshToken3) => {
  const verifiedRefreshToken = jwtUtils.verifyToken(
    refreshToken3,
    config_default.refresh_token_secret_key
  );
  if (!verifiedRefreshToken.success) {
    throw new Error(verifiedRefreshToken.error);
  }
  const { id } = verifiedRefreshToken.data;
  const user = await prisma.user.findUniqueOrThrow({
    where: {
      id
    }
  });
  if (user.status === "BLOCKED") {
    throw new Error("User blocked");
  }
  const jwtPayload = {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role
  };
  const accessToken = jwtUtils.createToken(
    jwtPayload,
    config_default.access_token_secret_key,
    { expiresIn: config_default.access_token_expire_in }
  );
  return {
    accessToken
  };
};
var googleClient = new OAuth2Client(config_default.google_client_id);
var googleLogin = async (credential, role) => {
  const ticket = await googleClient.verifyIdToken({
    idToken: credential,
    audience: config_default.google_client_id
  });
  const payload = ticket.getPayload();
  if (!payload?.email) {
    throw new Error("Google account email not found");
  }
  const email = payload.email;
  const name = payload.name || "Google User";
  const photoUrl = payload.picture || null;
  let user = await prisma.user.findUnique({
    where: {
      email
    }
  });
  if (user) {
    if (user.role === "ADMIN") {
      throw new Error("Admin cannot login with Google");
    }
    user = await prisma.user.update({
      where: {
        id: user.id
      },
      data: {
        photoUrl: photoUrl || user.photoUrl
      }
    });
  } else {
    if (!role) {
      throw new Error(
        "Please select Customer or Provider before creating an account"
      );
    }
    const randomPassword = crypto.randomUUID();
    const hashPassword = await bcrypt.hash(
      randomPassword,
      Number(config_default.bcrypt_hash_pass)
    );
    user = await prisma.user.create({
      data: {
        name,
        email,
        password: hashPassword,
        photoUrl,
        role
      }
    });
  }
  const jwtPayload = {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role
  };
  const accessToken = jwtUtils.createToken(
    jwtPayload,
    config_default.access_token_secret_key,
    {
      expiresIn: config_default.access_token_expire_in
    }
  );
  const refreshToken3 = jwtUtils.createToken(
    jwtPayload,
    config_default.refresh_token_secret_key,
    {
      expiresIn: config_default.refresh_token_expire_in
    }
  );
  return {
    user,
    accessToken,
    refreshToken: refreshToken3
  };
};
var authService = {
  createUserIntoDB,
  loginUser,
  getMyProfile,
  refreshToken,
  googleLogin
};

// src/modular/auth/auth.controller.ts
import httpStatus from "http-status";

// utiles/catchAsync.ts
var catchAsync = (fn) => {
  return async (req, res, next) => {
    try {
      await fn(req, res, next);
    } catch (error) {
      console.log(error);
      next(error);
    }
  };
};

// utiles/sendResponse.ts
var sendResponse = (res, data) => {
  res.status(data.statusCode).json({
    success: data.success,
    statusCode: data.statusCode,
    message: data.message,
    data: data.data
  });
};

// src/config/cloudinary.ts
import { v2 as cloudinary } from "cloudinary";
cloudinary.config({
  cloud_name: config_default.cloudinary_cloud_name,
  api_key: config_default.cloudinary_api_key,
  api_secret: config_default.cloudinary_api_secret
});
var cloudinary_default = cloudinary;

// utiles/xcloudinaryUpload.ts
var uploadToCloudinary = (fileBuffer) => {
  return new Promise((resolve, reject) => {
    const uploadStream = cloudinary_default.uploader.upload_stream(
      {
        folder: "gearup/users"
      },
      (error, result) => {
        if (error) {
          return reject(error);
        }
        if (!result) {
          return reject(
            new Error("Cloudinary upload failed")
          );
        }
        resolve(result.secure_url);
      }
    );
    uploadStream.end(fileBuffer);
  });
};

// src/modular/auth/auth.controller.ts
var createUser = catchAsync(
  async (req, res, next) => {
    const body = req.body;
    if (req.file) {
      const photoUrl = await uploadToCloudinary(req.file.buffer);
      body.photoUrl = photoUrl;
    }
    const result = await authService.createUserIntoDB(body);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus.CREATED,
      message: "User created successfully",
      data: {
        result
      }
    });
  }
);
var loginUser2 = catchAsync(
  async (req, res, next) => {
    const body = req.body;
    const { accessToken, refreshToken: refreshToken3 } = await authService.loginUser(body);
    res.cookie("accessToken", accessToken, {
      httpOnly: true,
      sameSite: "none",
      secure: false,
      maxAge: 1e3 * 60 * 60 * 24
    });
    res.cookie("refreshToken", refreshToken3, {
      httpOnly: true,
      secure: false,
      sameSite: "none",
      maxAge: 1e3 * 60 * 60 * 24 * 7
    });
    sendResponse(res, {
      success: true,
      statusCode: httpStatus.OK,
      message: "User login successfully",
      data: {
        accessToken,
        refreshToken: refreshToken3
      }
    });
  }
);
var getMyProfile2 = catchAsync(
  async (req, res, next) => {
    const result = await authService.getMyProfile(req.user?.id);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus.OK,
      message: "Get my profile",
      data: result
    });
  }
);
var refreshToken2 = catchAsync(
  async (req, res, next) => {
    const refreshToken3 = req.cookies.refreshToken;
    const { accessToken } = await authService.refreshToken(refreshToken3);
    res.cookie("accessToken", accessToken, {
      httpOnly: true,
      sameSite: "lax",
      secure: false,
      maxAge: 1e3 * 60 * 60 * 24
    });
    sendResponse(res, {
      success: true,
      statusCode: httpStatus.OK,
      message: "Refresh token retrieved",
      data: {
        accessToken
      }
    });
  }
);
var googleLogin2 = catchAsync(async (req, res) => {
  const { credential, role } = req.body;
  if (!credential) {
    throw new Error("Google credential is required");
  }
  const result = await authService.googleLogin(credential, role);
  res.cookie("accessToken", result.accessToken, {
    httpOnly: true,
    secure: config_default.node_env === "production",
    sameSite: "lax"
  });
  res.cookie("refreshToken", result.refreshToken, {
    httpOnly: true,
    secure: config_default.node_env === "production",
    sameSite: "lax"
  });
  sendResponse(res, {
    success: true,
    statusCode: httpStatus.OK,
    message: "Google login successful",
    data: {
      user: {
        id: result.user.id,
        name: result.user.name,
        email: result.user.email,
        role: result.user.role,
        photoUrl: result.user.photoUrl
      }
    }
  });
});
var authController = {
  createUser,
  loginUser: loginUser2,
  getMyProfile: getMyProfile2,
  refreshToken: refreshToken2,
  googleLogin: googleLogin2
};

// src/middleware/auth.ts
import httpStatus2 from "http-status";
var auth = (...requiredRole) => {
  return catchAsync(async (req, res, next) => {
    const token = req.cookies.accessToken ? req.cookies.accessToken : req.headers.authorization?.startsWith("Bearer") ? req.headers.authorization?.split(" ")[1] : req.headers.authorization;
    if (!token) {
      throw new Error("You are not log in");
    }
    const verified = jwtUtils.verifyToken(
      token,
      config_default.access_token_secret_key
    );
    if (!verified.success) {
      throw new Error(verified.error);
    }
    const { email, name, id, role } = verified.data;
    if (requiredRole.length && !requiredRole.includes(role)) {
      return res.status(403).json({
        success: false,
        statusCode: httpStatus2.FORBIDDEN,
        message: "Forbidden,you don't have permission this route ! Because you r not owner"
      });
    }
    const user = await prisma.user.findUnique({
      where: {
        id,
        email,
        name,
        role
      }
    });
    if (!user) {
      throw new Error("Please Login in");
    }
    if (user.status === "BLOCKED") {
      throw new Error("YOU account has been blocked");
    }
    req.user = {
      id,
      name,
      role,
      email
    };
    next();
  });
};

// src/lib/multer.ts
import multer from "multer";
var storage = multer.memoryStorage();
var upload = multer({
  storage
});
var multer_default = upload;

// src/modular/auth/auth.route.ts
var router = Router();
router.post("/register", multer_default.single("photo"), authController.createUser);
router.post("/google", authController.googleLogin);
router.post("/login", authController.loginUser);
router.get(
  "/me",
  auth(UserRole.ADMIN, UserRole.CUSTOMER, UserRole.PROVIDER),
  authController.getMyProfile
);
router.post("/refreshToken", authController.refreshToken);
var authRouter = router;

// src/modular/category/category.route.ts
import { Router as Router2 } from "express";

// src/modular/category/category.service.ts
var createCategory = async (payload, adminId) => {
  const { name } = payload;
  const findCategory = await prisma.category.findUnique({
    where: {
      name
    }
  });
  if (findCategory) {
    throw new Error("Category already exist");
  }
  const category = await prisma.category.create({
    data: {
      name,
      createdBy: adminId
    }
  });
  return category;
};
var getAllCategory = async () => {
  const findMany = await prisma.category.findMany({
    orderBy: {
      createdAt: "desc"
    },
    include: {
      admin: {
        select: {
          id: true,
          email: true,
          name: true
        }
      }
    }
  });
  return findMany;
};
var categoryService = {
  createCategory,
  getAllCategory
};

// src/modular/category/category.controller.ts
import httpStatus3 from "http-status";
var createCategory2 = catchAsync(async (req, res, next) => {
  const payload = req.body;
  const adminId = req.user?.id;
  const result = await categoryService.createCategory(payload, adminId);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus3.CREATED,
    message: "Category create successfully",
    data: result
  });
});
var getAllCategory2 = catchAsync(async (req, res, next) => {
  const result = await categoryService.getAllCategory();
  sendResponse(res, {
    success: true,
    statusCode: httpStatus3.OK,
    message: "All category here",
    data: result
  });
});
var categoryController = {
  createCategory: createCategory2,
  getAllCategory: getAllCategory2
};

// src/modular/category/category.route.ts
var router2 = Router2();
router2.post("/", auth(UserRole.ADMIN), categoryController.createCategory);
router2.get("/", categoryController.getAllCategory);
var categoryRouter = router2;

// src/modular/gear/gear.route.ts
import { Router as Router3 } from "express";

// src/modular/gear/gear.service.ts
var getAllGear = async (query) => {
  const minPrice = query.minPrice ? Number(query.minPrice) : void 0;
  const maxPrice = query.maxPrice ? Number(query.maxPrice) : void 0;
  const andCondition = [];
  if (query.brand) {
    andCondition.push({
      brand: {
        contains: query.brand,
        mode: "insensitive"
      }
    });
  }
  if (query.category) {
    andCondition.push({
      category: {
        name: {
          contains: query.category,
          mode: "insensitive"
        }
      }
    });
  }
  if (minPrice !== void 0 || maxPrice !== void 0) {
    andCondition.push({
      pricePerDay: {
        ...minPrice !== void 0 && {
          gte: minPrice
        },
        ...maxPrice !== void 0 && {
          lte: maxPrice
        }
      }
    });
  }
  if (query.startDate && query.endDate) {
    const startDate = new Date(query.startDate);
    const endDate = new Date(query.endDate);
    andCondition.push({
      NOT: {
        rental: {
          some: {
            status: {
              in: [
                "PLACED",
                "CONFIRMED",
                "PAID",
                "PICKED_UP"
              ]
            },
            AND: [
              {
                startDate: {
                  lte: endDate
                }
              },
              {
                endDate: {
                  gte: startDate
                }
              }
            ]
          }
        }
      }
    });
  }
  const gear = await prisma.gear.findMany({
    where: {
      AND: andCondition
    },
    include: {
      category: true,
      provider: {
        select: {
          id: true,
          name: true,
          email: true,
          role: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return gear;
};
var getGearById = async (id) => {
  const gear = await prisma.gear.findUnique({
    where: {
      id
    },
    include: {
      category: true,
      provider: {
        select: {
          id: true,
          name: true,
          email: true,
          role: true
        }
      }
    }
  });
  return gear;
};
var gearService = {
  getAllGear,
  getGearById
};

// src/modular/gear/gear.contoller.ts
import httpStatus4 from "http-status";
var getAllGear2 = catchAsync(async (req, res, next) => {
  const query = req.query;
  const result = await gearService.getAllGear(query);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus4.OK,
    message: "Get all gear",
    data: result
  });
});
var getGearById2 = catchAsync(async (req, res, next) => {
  const id = req.params.id;
  const result = await gearService.getGearById(id);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus4.CREATED,
    message: "Gear create successfully",
    data: result
  });
});
var gearController = {
  getAllGear: getAllGear2,
  getGearById: getGearById2
};

// src/modular/gear/gear.route.ts
var router3 = Router3();
router3.get("/", gearController.getAllGear);
router3.get("/:id", gearController.getGearById);
var gearRouter = router3;

// src/modular/rentals/rental.route.ts
import { Router as Router4 } from "express";

// src/modular/rentals/rental.service.ts
var createRental = async (payload, customerId) => {
  const { startDate, endDate, gearId } = payload;
  const gear = await prisma.gear.findUnique({
    where: {
      id: gearId
    }
  });
  if (!gear) {
    throw new Error("Gear not found");
  }
  if (gear.status !== GearStatus.AVAILABLE) {
    throw new Error("Gear is not available");
  }
  if (gear.quantity <= 0) {
    throw new Error("Gear is out of stock");
  }
  const startDateNew = new Date(startDate);
  const endDateNew = new Date(endDate);
  if (endDateNew <= startDateNew) {
    throw new Error("End date must be after start date");
  }
  const totalDays = Math.ceil(
    (endDateNew.getTime() - startDateNew.getTime()) / (1e3 * 60 * 60 * 24)
  );
  const totalPrice = totalDays * gear.pricePerDay;
  const transactionResult = await prisma.$transaction(async (tx) => {
    const rental = await tx.rental.create({
      data: {
        startDate: startDateNew,
        endDate: endDateNew,
        customerId,
        gearId,
        totalPrice,
        totalDays
      },
      include: {
        gear: true,
        customer: {
          select: {
            id: true,
            name: true,
            email: true
          }
        }
      }
    });
    await tx.gear.update({
      where: {
        id: gearId
      },
      data: {
        quantity: {
          decrement: 1
        }
      }
    });
    return rental;
  });
  return transactionResult;
};
var getRental = async (customerId) => {
  const rental = await prisma.rental.findMany({
    where: {
      customerId
    },
    include: {
      customer: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      gear: {
        include: {
          category: true
        }
      },
      // payment call kora
      payment: true
    }
  });
  if (!rental) {
    throw new Error("Rental not found");
  }
  if (rental.length === 0) {
    throw new Error("Plz created rental data");
  }
  return rental;
};
var getRentalById = async (id) => {
  const rental = await prisma.rental.findUnique({
    where: {
      id
    },
    include: {
      customer: {
        select: {
          id: true,
          name: true,
          email: true
        }
      },
      gear: {
        include: {
          category: true
        }
      }
    }
  });
  return rental;
};
var rentalService = {
  createRental,
  getRental,
  getRentalById
};

// src/modular/rentals/rental.controller.ts
import httpStatus5 from "http-status";
var createRental2 = catchAsync(async (req, res) => {
  const customerId = req.user?.id;
  const payload = req.body;
  const result = await rentalService.createRental(payload, customerId);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus5.CREATED,
    message: "Rental created successfully",
    data: result
  });
});
var getRental2 = catchAsync(async (req, res, nex) => {
  const customerId = req.user?.id;
  const result = await rentalService.getRental(customerId);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus5.OK,
    message: "Rental retrieved successfully",
    data: result
  });
});
var getRentalById2 = catchAsync(async (req, res, next) => {
  const { id } = req.params;
  const result = await rentalService.getRentalById(id);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus5.OK,
    message: "Rental retrieved successfully",
    data: result
  });
});
var rentalController = {
  createRental: createRental2,
  getRental: getRental2,
  getRentalById: getRentalById2
};

// src/modular/rentals/rental.route.ts
var router4 = Router4();
router4.post(
  "/",
  auth(UserRole.CUSTOMER),
  rentalController.createRental
);
router4.get("/", auth(UserRole.CUSTOMER), rentalController.getRental);
router4.get("/:id", auth(UserRole.CUSTOMER), rentalController.getRentalById);
var rentalRouter = router4;

// src/modular/reviews/review.route.ts
import { Router as Router5 } from "express";

// src/modular/reviews/review.service.ts
var createReview = async (payload, customerId) => {
  const { rentalId, rating, comment } = payload;
  const rental = await prisma.rental.findUnique({
    where: {
      id: rentalId
    }
  });
  if (!rental) {
    throw new Error("Rental not round");
  }
  if (rental.customerId !== customerId) {
    throw new Error("You can review on your own rental");
  }
  if (rental.status !== RentalStatus.RETURNED) {
    throw new Error("You can review only after returning the gear");
  }
  const existingReview = await prisma.review.findUnique({
    where: {
      rentalId
    }
  });
  if (existingReview) {
    throw new Error("You have already created review");
  }
  const review = await prisma.review.create({
    data: {
      rating,
      comment,
      rentalId,
      customerId,
      gearId: rental.gearId
    }
  });
  return review;
};
var getMyReviews = async (customerId) => {
  const reviews = await prisma.review.findMany({
    where: {
      customerId
    },
    orderBy: {
      createdAt: "desc"
    },
    include: {
      gear: {
        select: {
          id: true,
          title: true,
          brand: true,
          image: true
        }
      },
      rental: {
        select: {
          id: true,
          status: true,
          startDate: true,
          endDate: true
        }
      }
    }
  });
  return reviews;
};
var reviewService = {
  createReview,
  getMyReviews
};

// src/modular/reviews/review.controller.ts
import httpStatus6 from "http-status";
var createReview2 = catchAsync(
  async (req, res, next) => {
    const customerId = req.user?.id;
    const payload = req.body;
    const result = await reviewService.createReview(
      payload,
      customerId
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus6.CREATED,
      message: "Review created successfully",
      data: result
    });
  }
);
var getMyReviews2 = catchAsync(
  async (req, res, next) => {
    const customerId = req.user?.id;
    const result = await reviewService.getMyReviews(customerId);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus6.OK,
      message: "My reviews retrieved successfully",
      data: result
    });
  }
);
var reviewController = {
  createReview: createReview2,
  getMyReviews: getMyReviews2
};

// src/modular/reviews/review.route.ts
var router5 = Router5();
router5.post("/", auth(UserRole.CUSTOMER), reviewController.createReview);
router5.get("/my-reviews", auth(UserRole.CUSTOMER), reviewController.getMyReviews);
var reviewRouter = router5;

// src/provider/provider.route.ts
import { Router as Router6 } from "express";

// src/provider/provider.service.ts
var createGearByProvider = async (payload, providerId) => {
  const {
    title,
    description,
    brand,
    pricePerDay,
    image,
    quantity,
    categoryId,
    status
  } = payload;
  const category = await prisma.category.findUnique({
    where: {
      id: categoryId
    }
  });
  if (!category) {
    throw new Error("Category not found");
  }
  const existingGear = await prisma.gear.findFirst({
    where: {
      title,
      brand,
      providerId
    }
  });
  if (existingGear) {
    throw new Error("Title brand already existing the gear");
  }
  const result = await prisma.gear.create({
    data: {
      title,
      brand,
      description,
      pricePerDay,
      image,
      quantity,
      categoryId,
      providerId,
      status
    },
    include: {
      category: true,
      provider: {
        select: {
          id: true,
          name: true,
          email: true,
          role: true
        }
      }
    }
  });
  return result;
};
var getGearByProvider = async (providerId) => {
  const gears = await prisma.gear.findMany({
    where: {
      providerId
    },
    include: {
      category: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return gears;
};
var putGearByProvider = async (providerId, gearId, payload) => {
  const gear = await prisma.gear.findUnique({
    where: {
      id: gearId
    }
  });
  if (!gear) {
    throw new Error("Gear not found !");
  }
  if (gear.providerId !== providerId) {
    throw new Error("You are not the owner of this gear");
  }
  if (payload.categoryId) {
    const category = await prisma.category.findUnique({
      where: {
        id: payload.categoryId
      }
    });
    if (!category) {
      throw new Error("Category not found");
    }
  }
  const update = await prisma.gear.update({
    where: {
      id: gearId
    },
    data: payload,
    include: {
      category: true,
      provider: {
        select: {
          id: true,
          name: true,
          email: true,
          role: true
        }
      }
    }
  });
  return update;
};
var deleteGearByProvider = async (gearId, providerId) => {
  const gear = await prisma.gear.findUnique({
    where: {
      id: gearId
    }
  });
  if (!gear) {
    throw new Error("Gear not found!");
  }
  if (gear.providerId !== providerId) {
    throw new Error("You are not the owner of this gear");
  }
  const rentalExists = await prisma.rental.findFirst({
    where: {
      gearId
    }
  });
  if (rentalExists) {
    throw new Error(
      "Cannot delete this gear because it has rental history"
    );
  }
  const deletedGear = await prisma.gear.delete({
    where: {
      id: gearId
    }
  });
  return deletedGear;
};
var orderGetByProvider = async (providerId) => {
  const result = await prisma.rental.findMany({
    where: {
      gear: {
        providerId
      }
    },
    include: {
      gear: {
        select: {
          id: true,
          title: true,
          brand: true,
          pricePerDay: true,
          status: true
        }
      },
      customer: {
        select: {
          id: true,
          name: true,
          email: true,
          role: true,
          status: true
        }
      }
    }
  });
  return result;
};
var updateOrderByProviderStatus = async (rentalId, providerId, payload) => {
  const { status } = payload;
  const rental = await prisma.rental.findUnique({
    where: {
      id: rentalId
    }
  });
  if (!rental) {
    throw new Error("Rental not found");
  }
  const gear = await prisma.gear.findUnique({
    where: {
      id: rental.gearId
    }
  });
  if (!gear || gear.providerId !== providerId) {
    throw new Error("You are not the owner of this order");
  }
  const allowedStatusTransition = {
    PLACED: ["CONFIRMED", "CANCELLED"],
    CONFIRMED: ["PAID"],
    PAID: ["PICKED_UP"],
    PICKED_UP: ["RETURNED"],
    RETURNED: [],
    CANCELLED: []
  };
  const currentStatus = rental.status;
  if (!allowedStatusTransition[currentStatus]?.includes(status)) {
    throw new Error(`Cannot change status from ${currentStatus} to ${status}`);
  }
  const transactionResult = await prisma.$transaction(async (tx) => {
    const updateStatus = await tx.rental.update({
      where: {
        id: rentalId
      },
      data: {
        status
      },
      include: {
        gear: {
          select: {
            id: true,
            title: true,
            brand: true,
            pricePerDay: true,
            status: true
          }
        },
        customer: {
          select: {
            id: true,
            name: true,
            email: true,
            role: true,
            status: true
          }
        }
      }
    });
    if (status === "CANCELLED") {
      await tx.gear.update({
        where: {
          id: rental.gearId
        },
        data: {
          quantity: {
            increment: 1
          }
        }
      });
    }
    return updateStatus;
  });
  return transactionResult;
};
var providerService = {
  deleteGearByProvider,
  createGearByProvider,
  putGearByProvider,
  orderGetByProvider,
  updateOrderByProviderStatus,
  getGearByProvider
};

// src/provider/provider.controller.ts
import httpStatus7 from "http-status";
var createGearByProvider2 = catchAsync(
  async (req, res, next) => {
    const payload = req.body;
    const userId = req.user?.id;
    const result = await providerService.createGearByProvider(
      payload,
      userId
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.CREATED,
      message: "Gear create successfully",
      data: result
    });
  }
);
var getGearByProvider2 = catchAsync(
  async (req, res, next) => {
    const providerId = req.user?.id;
    const result = await providerService.getGearByProvider(
      providerId
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.OK,
      message: "Provider gears retrieved successfully",
      data: result
    });
  }
);
var putGearByProvider2 = catchAsync(
  async (req, res, next) => {
    const providerId = req.user?.id;
    const { id } = req.params;
    const body = req.body;
    const result = await providerService.putGearByProvider(providerId, id, body);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.CREATED,
      message: "Gear Updated successfully",
      data: result
    });
  }
);
var deleteGearByProvider2 = catchAsync(
  async (req, res, next) => {
    const { id } = req.params;
    const providerId = req.user?.id;
    await providerService.deleteGearByProvider(id, providerId);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus7.CREATED,
      message: "Gear Delete successfully",
      data: null
    });
  }
);
var orderGetByProvider2 = catchAsync(async (req, res, next) => {
  const providerId = req.user?.id;
  const result = await providerService.orderGetByProvider(providerId);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus7.CREATED,
    message: "Orders get successfully",
    data: result
  });
});
var updateOrderByProviderStatus2 = catchAsync(async (req, res, next) => {
  const providerId = req.user?.id;
  const id = req.params.id;
  const body = req.body;
  const result = await providerService.updateOrderByProviderStatus(id, providerId, body);
  sendResponse(res, {
    success: true,
    statusCode: httpStatus7.CREATED,
    message: "Orders status updated successfully by provider",
    data: result
  });
});
var providerController = {
  deleteGearByProvider: deleteGearByProvider2,
  createGearByProvider: createGearByProvider2,
  putGearByProvider: putGearByProvider2,
  orderGetByProvider: orderGetByProvider2,
  updateOrderByProviderStatus: updateOrderByProviderStatus2,
  getGearByProvider: getGearByProvider2
};

// src/provider/provider.route.ts
var router6 = Router6();
router6.post("/gear", auth(UserRole.PROVIDER), providerController.createGearByProvider);
router6.put("/gear/:id", auth(UserRole.PROVIDER), providerController.putGearByProvider);
router6.delete("/gear/:id", auth(UserRole.PROVIDER), providerController.deleteGearByProvider);
router6.get("/orders", auth(UserRole.PROVIDER), providerController.orderGetByProvider);
router6.patch("/orders/:id", auth(UserRole.PROVIDER), providerController.updateOrderByProviderStatus);
router6.get(
  "/gear",
  auth(UserRole.PROVIDER),
  providerController.getGearByProvider
);
var providerRouter = router6;

// src/middleware/notFound.ts
var notFound = (req, res) => {
  res.status(404).json({
    success: false,
    message: "Route not Found",
    path: req.originalUrl,
    date: Date()
  });
};

// src/middleware/globalErrorHandler.ts
import httpStatus8 from "http-status";
var globalErrorHandler = (err, req, res, next) => {
  let statusCode;
  let errorMessage = err.message || "Internal Server Error";
  let errorName = err.name || "Internal Server Error";
  if (err instanceof prismaNamespace_exports.PrismaClientValidationError) {
    statusCode = httpStatus8.BAD_REQUEST;
    errorMessage = "You have provided incorrect field type or missing fields";
  } else if (err instanceof prismaNamespace_exports.PrismaClientKnownRequestError) {
    if (err.code === "P2002") {
      statusCode = httpStatus8.BAD_REQUEST, errorMessage = "Duplicate Key Error";
    } else if (err.code === "P2003") {
      statusCode = httpStatus8.BAD_REQUEST, errorMessage = "Foreign key constraint failed";
    } else if (err.code === "P2025") {
      statusCode = httpStatus8.BAD_REQUEST, errorMessage = "An operation failed because it depends on one or more records that were required but not found.";
    }
  } else if (err instanceof prismaNamespace_exports.PrismaClientInitializationError) {
    if (err.errorCode === "P1000") {
      statusCode = httpStatus8.UNAUTHORIZED;
      errorMessage = "Authentication failed against database server. Please Check Your Credentials";
    } else if (err.errorCode === "P1001") {
      statusCode = httpStatus8.BAD_REQUEST;
      errorMessage = "Can't reach database server";
    }
  } else if (err instanceof prismaNamespace_exports.PrismaClientUnknownRequestError) {
    statusCode = httpStatus8.INTERNAL_SERVER_ERROR;
    errorMessage = "Error occurred during query execution";
  }
  res.status(httpStatus8.INTERNAL_SERVER_ERROR).json({
    success: false,
    statusCode: statusCode || httpStatus8.INTERNAL_SERVER_ERROR,
    name: errorName,
    message: errorMessage,
    error: err.stack
  });
};

// src/modular/admin/admin.route.ts
import { Router as Router7 } from "express";

// src/modular/admin/admin.controller.ts
import httpStatus9 from "http-status";

// src/modular/admin/admin.service.ts
var getUsers = async () => {
  const result = await prisma.user.findMany({
    orderBy: {
      createdAt: "desc"
    },
    omit: {
      password: true
    }
  });
  return result;
};
var patchUserStatus = async (userId, payload) => {
  const { status } = payload;
  const user = await prisma.user.findUnique({
    where: {
      id: userId
    }
  });
  if (!user) {
    throw new Error("User not found");
  }
  const result = await prisma.user.update({
    where: {
      id: userId
    },
    data: {
      status
    }
  });
  return result;
};
var getGear = async () => {
  const gear = await prisma.gear.findMany({
    orderBy: {
      createdAt: "desc"
    },
    include: {
      provider: {
        select: {
          id: true,
          name: true,
          email: true,
          role: true,
          status: true
        }
      }
    }
  });
  return gear;
};
var getRental3 = async () => {
  const rental = await prisma.rental.findMany({
    orderBy: {
      createdAt: "desc"
    },
    include: {
      customer: {
        select: {
          name: true,
          email: true,
          role: true,
          status: true
        }
      },
      gear: {
        include: {
          provider: {
            select: {
              id: true,
              name: true,
              email: true,
              role: true
            }
          }
        }
      }
    }
  });
  return rental;
};
var adminService = {
  getUsers,
  patchUserStatus,
  getGear,
  getRental: getRental3
};

// src/modular/admin/admin.controller.ts
var getUsers2 = catchAsync(
  async (req, res, next) => {
    const result = await adminService.getUsers();
    sendResponse(res, {
      success: true,
      statusCode: httpStatus9.CREATED,
      message: "Get all users successfully",
      data: result
    });
  }
);
var patchUserStatus2 = catchAsync(
  async (req, res, next) => {
    const id = req.params.id;
    const body = req.body;
    const result = await adminService.patchUserStatus(id, body);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus9.CREATED,
      message: "User status updated successfully",
      data: result
    });
  }
);
var getGear2 = catchAsync(
  async (req, res, next) => {
    const result = await adminService.getGear();
    sendResponse(res, {
      success: true,
      statusCode: httpStatus9.CREATED,
      message: "Get gear successfully",
      data: result
    });
  }
);
var getRental4 = catchAsync(
  async (req, res, next) => {
    const result = await adminService.getRental();
    sendResponse(res, {
      success: true,
      statusCode: httpStatus9.CREATED,
      message: "Get rental successfully",
      data: result
    });
  }
);
var adminController = {
  getUsers: getUsers2,
  patchUserStatus: patchUserStatus2,
  getGear: getGear2,
  getRental: getRental4
};

// src/modular/admin/admin.route.ts
var router7 = Router7();
router7.get("/users", auth(UserRole.ADMIN), adminController.getUsers);
router7.patch("/users/:id", auth(UserRole.ADMIN), adminController.patchUserStatus);
router7.get("/gear", auth(UserRole.ADMIN), adminController.getGear);
router7.get("/rentals", auth(UserRole.ADMIN), adminController.getRental);
var adminRouter = router7;

// src/modular/payment/payment.route.ts
import { Router as Router8 } from "express";

// src/modular/payment/payment.controller.ts
import httpStatus10 from "http-status";

// src/modular/payment/payment.service.ts
import Stripe from "stripe";
var stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
var createPayment = async (userId, payload) => {
  const { rentalId } = payload;
  const rental = await prisma.rental.findUniqueOrThrow({
    where: {
      id: rentalId
    },
    include: {
      gear: true
    }
  });
  if (rental.customerId !== userId) {
    throw new Error("You can pay only for your own rental");
  }
  if (rental.status !== "CONFIRMED") {
    throw new Error(
      "Payment is only available after provider confirms the rental"
    );
  }
  const existingPayment = await prisma.payment.findUnique({
    where: {
      rentalId
    }
  });
  if (existingPayment?.status === "PAID") {
    throw new Error("Payment already completed for this rental");
  }
  const session = await stripe.checkout.sessions.create({
    line_items: [
      {
        price_data: {
          currency: "usd",
          product_data: {
            name: rental.gear.title
          },
          unit_amount: Number(rental.totalPrice) * 100
        },
        quantity: 1
      }
    ],
    mode: "payment",
    payment_method_types: ["card"],
    success_url: `${config_default.app_url}/payment/success?session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: `${config_default.app_url}/payment/cancel`,
    metadata: {
      rentalId: rental.id,
      userId
    }
  });
  if (existingPayment) {
    const updatedPayment = await prisma.payment.update({
      where: {
        id: existingPayment.id
      },
      data: {
        transactionId: session.id,
        amount: rental.totalPrice,
        currency: "usd",
        status: "PENDING",
        paymentMethod: "STRIPE"
      }
    });
    return {
      payment: updatedPayment,
      paymentUrl: session.url
    };
  }
  const payment = await prisma.payment.create({
    data: {
      rentalId: rental.id,
      amount: rental.totalPrice,
      currency: "usd",
      status: "PENDING",
      paymentMethod: "STRIPE",
      transactionId: session.id
    }
  });
  return {
    payment,
    paymentUrl: session.url
  };
};
var confirmPayment = async (sessionId) => {
  const session = await stripe.checkout.sessions.retrieve(sessionId);
  if (session.payment_status !== "paid") {
    throw new Error("Payment is not completed");
  }
  const payment = await prisma.payment.findUniqueOrThrow({
    where: {
      transactionId: sessionId
    }
  });
  if (payment.status === "PAID") {
    await prisma.rental.update({
      where: {
        id: payment.rentalId
      },
      data: {
        status: "PAID"
      }
    });
    return payment;
  }
  const result = await prisma.$transaction(async (tx) => {
    const updatedPayment = await tx.payment.update({
      where: {
        id: payment.id
      },
      data: {
        status: "PAID"
      }
    });
    await tx.rental.update({
      where: {
        id: payment.rentalId
      },
      data: {
        status: "PAID"
      }
    });
    return updatedPayment;
  });
  return result;
};
var getPayment = async (userId) => {
  const payments = await prisma.payment.findMany({
    where: {
      rental: {
        customerId: userId
      }
    },
    include: {
      rental: {
        include: {
          gear: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return payments;
};
var getPaymentById = async (paymentId, userId) => {
  const payment = await prisma.payment.findFirstOrThrow({
    where: {
      id: paymentId,
      rental: {
        customerId: userId
      }
    },
    include: {
      rental: {
        include: {
          gear: true
        }
      }
    }
  });
  return payment;
};
var paymentService = {
  createPayment,
  confirmPayment,
  getPayment,
  getPaymentById
};

// src/modular/payment/payment.controller.ts
var createPayment2 = catchAsync(
  async (req, res, next) => {
    const userId = req.user?.id;
    const body = req.body;
    const result = await paymentService.createPayment(userId, body);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus10.CREATED,
      message: "Payment created successfully",
      data: result
    });
  }
);
var confirmPayment2 = catchAsync(
  async (req, res, next) => {
    const { session } = req.body;
    const result = await paymentService.confirmPayment(session);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus10.OK,
      message: "Payment confirmed successfully",
      data: result
    });
  }
);
var getPayment2 = catchAsync(
  async (req, res, next) => {
    const userId = req.user?.id;
    const result = await paymentService.getPayment(userId);
    sendResponse(res, {
      success: true,
      statusCode: httpStatus10.OK,
      message: "Payment history retrieved successfully",
      data: result
    });
  }
);
var getPaymentById2 = catchAsync(
  async (req, res, next) => {
    const { id } = req.params;
    const userId = req.user?.id;
    const result = await paymentService.getPaymentById(
      id,
      userId
    );
    sendResponse(res, {
      success: true,
      statusCode: httpStatus10.OK,
      message: "Payment details retrieved successfully",
      data: result
    });
  }
);
var paymentController = {
  createPayment: createPayment2,
  confirmPayment: confirmPayment2,
  getPayment: getPayment2,
  getPaymentById: getPaymentById2
};

// src/modular/payment/payment.route.ts
var router8 = Router8();
router8.post("/create", auth(UserRole.CUSTOMER), paymentController.createPayment);
router8.post("/confirm", auth(UserRole.CUSTOMER), paymentController.confirmPayment);
router8.get("/", auth(UserRole.CUSTOMER), paymentController.getPayment);
router8.get("/:id", auth(UserRole.CUSTOMER), paymentController.getPaymentById);
var paymentRouter = router8;

// src/app.ts
var app = express();
app.use(cors({
  origin: config_default.app_url,
  credentials: true
}));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.get("/", (req, res) => {
  res.send("Hello World!");
});
app.use("/api/auth", authRouter);
app.use("/api/category", categoryRouter);
app.use("/api/gear", gearRouter);
app.use("/api/rental", rentalRouter);
app.use("/api/reviews", reviewRouter);
app.use("/api/provider", providerRouter);
app.use("/api/admin", adminRouter);
app.use("/api/payment", paymentRouter);
app.use(globalErrorHandler);
app.use(notFound);
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
